Repository over-time-worker/backend, pull requests merged in 2025-03, with the labels that each got.

#9 [OV-25] feat(gateway) : server 모듈 생성
  server/.gitattributes
  server/.gitignore
  server/build.gradle
  server/gradle/wrapper/gradle-wrapper.jar
  server/gradle/wrapper/gradle-wrapper.properties
  server/gradlew
  server/gradlew.bat
  server/settings.gradle
  server/src/main/java/com/owlexpress/server/ServerApplication.java
Labels: enhancement

#15 Feat(ai)/create hub delivery message
  ai/.gitattributes
  ai/.gitignore
  ai/build.gradle
  ai/gradle/wrapper/gradle-wrapper.jar
  ai/gradle/wrapper/gradle-wrapper.properties
  ai/gradlew
  ai/gradlew.bat
  ai/settings.gradle
  ai/src/main/java/com/owl_express/ai/AiApplication.java
  ai/src/main/java/com/owl_express/ai/application/AiService.java
  ai/src/main/java/com/owl_express/ai/application/dtos/CommonDto.java
  ai/src/main/java/com/owl_express/ai/application/dtos/MessageCreateRequestDto.java
  ai/src/main/java/com/owl_express/ai/application/dtos/MessageCreateResponseDto.java
  ai/src/main/java/com/owl_express/ai/application/dtos/MessageFindResponseDto.java
  ai/src/main/java/com/owl_express/ai/common/config/JpaConfig.java
  ai/src/main/java/com/owl_express/ai/common/config/QueryDslConfig.java
  ai/src/main/java/com/owl_express/ai/common/config/WebClientConfig.java
  ai/src/main/java/com/owl_express/ai/domain/entity/Ai.java
  ai/src/main/java/com/owl_express/ai/domain/entity/BaseEntity.java
  ai/src/main/java/com/owl_express/ai/domain/repository/AiRepository.java
  ai/src/main/java/com/owl_express/ai/infrastructure/AiJpaRepository.java
  ai/src/main/java/com/owl_express/ai/infrastructure/AiQueryRepository.java
  ai/src/main/java/com/owl_express/ai/infrastructure/AiQueryRepositoryImpl.java
  ai/src/main/java/com/owl_express/ai/infrastructure/AiRepositoryImpl.java
  ai/src/main/java/com/owl_express/ai/presentation/AiController.java
  ai/src/test/java/com/owl_express/ai/AiApplicationTests.java
  alarm/.gitattributes
  alarm/.gitignore
  alarm/build.gradle
  alarm/gradle/wrapper/gradle-wrapper.jar
  alarm/gradle/wrapper/gradle-wrapper.properties
  alarm/gradlew
  alarm/gradlew.bat
  alarm/settings.gradle
  alarm/src/main/java/com/owl_express/alarm/AlarmApplication.java
  alarm/src/main/resources/application.properties
  alarm/src/test/java/com/owl_express/alarm/AlarmApplicationTests.java
Labels: enhancement

#17 [OV-28] feat(product) : entity 개발
  product/.gitignore
  product/src/main/java/com/owlexpress/product/common/BaseEntity.java
  product/src/main/java/com/owlexpress/product/domain/HubInfo.java
  product/src/main/java/com/owlexpress/product/domain/Product.java
  product/src/main/java/com/owlexpress/product/domain/constant/ProductType.java
  product/src/main/resources/application.properties
Labels: enhancement

#20 Feat(ai)/create consumer delivery message
  ai/src/main/java/com/owl_express/ai/application/AiService.java
  ai/src/main/java/com/owl_express/ai/application/dtos/MessageCreateRequestDto.java
  ai/src/main/java/com/owl_express/ai/application/dtos/MessageCreateResponseDto.java
  ai/src/main/java/com/owl_express/ai/common/advice/GlobalExceptionAdvice.java
  ai/src/main/java/com/owl_express/ai/domain/entity/Ai.java
  ai/src/main/java/com/owl_express/ai/presentation/AiController.java
Labels: enhancement

#25 [OV-7] feat(user): 회원 모듈 생성 (#3)
  settings.gradle
  user/.gitattributes
  user/.gitignore
  user/build.gradle
  user/gradle/wrapper/gradle-wrapper.jar
  user/gradle/wrapper/gradle-wrapper.properties
  user/gradlew
  user/gradlew.bat
  user/settings.gradle
  user/src/main/java/user/UserApplication.java
  user/src/main/resources/application.yml
  user/src/test/java/user/UserApplicationTests.java
Labels: enhancement

#28 Feat(ai)/find ai message
  ai/build.gradle
  ai/src/main/java/com/owl_express/ai/application/AiService.java
  ai/src/main/java/com/owl_express/ai/application/AiServiceImpl.java
  ai/src/main/java/com/owl_express/ai/application/dtos/MessageCreateRequestDto.java
  ai/src/main/java/com/owl_express/ai/application/dtos/MessageCreateResponseDto.java
  ai/src/main/java/com/owl_express/ai/application/dtos/MessageFindResponseDto.java
  ai/src/main/java/com/owl_express/ai/application/exceptions/AiException.java
  ai/src/main/java/com/owl_express/ai/common/util/CommonUtil.java
  ai/src/main/java/com/owl_express/ai/domain/entity/Ai.java
  ai/src/main/java/com/owl_express/ai/domain/repository/AiRepository.java
  ai/src/main/java/com/owl_express/ai/infrastructure/AiRepositoryImpl.java
  ai/src/main/java/com/owl_express/ai/presentation/AiController.java
Labels: enhancement

#26 [OV-30] feat(product) : 상품 조회 기능 구현
  product/src/main/java/com/owlexpress/product/domain/service/ProductDomainService.java
  product/src/main/java/com/owlexpress/product/domain/service/ProductDomainServiceImpl.java
  product/src/main/java/com/owlexpress/product/presentation/ProductController.java
  product/src/main/java/com/owlexpress/product/presentation/dto/response/FindProductResponse.java
Labels: enhancement

#31 [OV-38] refactor(ai): 패키지 구조 리팩토링(#29)
  ai/src/main/java/com/owl_express/ai/application/dtos/request/MessageCreateRequestDto.java
  ai/src/main/java/com/owl_express/ai/application/dtos/response/MessageCreateResponseDto.java
  ai/src/main/java/com/owl_express/ai/application/dtos/response/MessageFindResponseDto.java
  ai/src/main/java/com/owl_express/ai/application/service/AiService.java
  ai/src/main/java/com/owl_express/ai/application/service/AiServiceImpl.java
  ai/src/main/java/com/owl_express/ai/presentation/AiController.java
Labels: refactor

#32 [OV-23] feat(user): 회원 도메인 생성 (#30)
  user/src/main/java/com/owlexpress/user/UserApplication.java
  user/src/main/java/com/owlexpress/user/common/BaseEntity.java
  user/src/main/java/com/owlexpress/user/domain/entity/User.java
  user/src/main/java/com/owlexpress/user/domain/vo/PlatformType.java
  user/src/main/java/com/owlexpress/user/domain/vo/Role.java
  user/src/main/resources/application-dev.yml
  user/src/main/resources/application-prod.yml
  user/src/main/resources/application-test.yml
  user/src/test/java/com/owlexpress/user/UserApplicationTests.java
Labels: enhancement

#37 [OV-31 , OV-37, OV-40, OV-41] Feat(Product) : 검색 기능 구현 , Refactor(Product) : 서비스 리팩토링
  product/build.gradle
  product/src/main/java/com/owlexpress/product/ProductApplication.java
  product/src/main/java/com/owlexpress/product/application/ProductHubUsecase.java
  product/src/main/java/com/owlexpress/product/application/dto/response/FindProductResponseDto.java
  product/src/main/java/com/owlexpress/product/application/dto/response/SearchProductResponseDto.java
  product/src/main/java/com/owlexpress/product/common/exceptions/GlobalExceptionAdvice.java
  product/src/main/java/com/owlexpress/product/common/exceptions/ProductException.java
  product/src/main/java/com/owlexpress/product/domain/entity/HubInfo.java
  product/src/main/java/com/owlexpress/product/domain/entity/Product.java
  product/src/main/java/com/owlexpress/product/domain/repository/HubInfoRepository.java
  product/src/main/java/com/owlexpress/product/domain/repository/ProductRepository.java
  product/src/main/java/com/owlexpress/product/domain/service/HubInfoService.java
  product/src/main/java/com/owlexpress/product/domain/service/HubInfoServiceImpl.java
  product/src/main/java/com/owlexpress/product/domain/service/ProductDomainService.java
  product/src/main/java/com/owlexpress/product/domain/service/ProductDomainServiceImpl.java
  product/src/main/java/com/owlexpress/product/infrastructure/ProductRepositoryImpl.java
  product/src/main/java/com/owlexpress/product/infrastructure/config/ProductSearchConfig.java
  product/src/main/java/com/owlexpress/product/infrastructure/config/QueryDslConfig.java
  product/src/main/java/com/owlexpress/product/infrastructure/feignClient/HubClient.java
  product/src/main/java/com/owlexpress/product/infrastructure/repository/HubInfoJpaRepository.java
  product/src/main/java/com/owlexpress/product/infrastructure/repository/HubInfoRepositoryImpl.java
  product/src/main/java/com/owlexpress/product/infrastructure/repository/ProductJpaRepository.java
  product/src/main/java/com/owlexpress/product/infrastructure/repository/ProductQueryDslRepository.java
  product/src/main/java/com/owlexpress/product/infrastructure/repository/ProductQueryDslRepositoryImpl.java
  product/src/main/java/com/owlexpress/product/infrastructure/repository/ProductRepositoryImpl.java
  product/src/main/java/com/owlexpress/product/presentation/HubInfoController.java
  product/src/main/java/com/owlexpress/product/presentation/ProductController.java
  product/src/main/java/com/owlexpress/product/presentation/dto/request/CreateHubInfoRequestDto.java
  product/src/main/java/com/owlexpress/product/presentation/dto/request/CreateProductRequestDto.java
  product/src/main/java/com/owlexpress/product/presentation/dto/request/UpdateHubInfoRequestDto.java
  product/src/main/java/com/owlexpress/product/presentation/dto/request/UpdateProductDto.java
  product/src/test/java/com/owlexpress/product/ProductApplicationTests.java
Labels: enhancement, refactor

#36 [OV-23] feat(auth): 액세스 토큰 발급 기능 추가 (#35)
  auth/src/main/java/com/owlexpress/auth/application/AuthService.java
  auth/src/main/java/com/owlexpress/auth/application/AuthServiceImpl.java
  auth/src/main/java/com/owlexpress/auth/application/dto/request/UserLoginRequestDto.java
  auth/src/main/java/com/owlexpress/auth/application/dto/response/UserInfoResponseDto.java
  auth/src/main/java/com/owlexpress/auth/common/TokenProvider.java
  auth/src/main/java/com/owlexpress/auth/infrastructure/UserClient.java
  auth/src/main/java/com/owlexpress/auth/presentation/AuthController.java
  auth/src/main/java/com/owlexpress/auth/presentation/dto/request/LoginRequestDto.java
  auth/src/main/java/com/owlexpress/auth/presentation/dto/response/TokenResponseDto.java
  auth/src/test/java/com/owlexpress/auth/AuthApplicationTests.java
Labels: enhancement

#47 [OV-52] feat(producer,auth) : 각 모듈 root에 포함
  settings.gradle
Labels: enhancement

#48 Feat(ai)/search message
  ai/build.gradle
  ai/src/main/java/com/owl_express/ai/application/dtos/response/MessageFindResponseDto.java
  ai/src/main/java/com/owl_express/ai/application/service/AiService.java
  ai/src/main/java/com/owl_express/ai/application/service/AiServiceImpl.java
  ai/src/main/java/com/owl_express/ai/common/util/PageUtil.java
  ai/src/main/java/com/owl_express/ai/common/util/QueryUtil.java
  ai/src/main/java/com/owl_express/ai/domain/entity/Ai.java
  ai/src/main/java/com/owl_express/ai/domain/repository/AiRepository.java
  ai/src/main/java/com/owl_express/ai/infrastructure/AiQueryRepository.java
  ai/src/main/java/com/owl_express/ai/infrastructure/AiQueryRepositoryImpl.java
  ai/src/main/java/com/owl_express/ai/infrastructure/AiRepositoryImpl.java
  ai/src/main/java/com/owl_express/ai/presentation/AiController.java
Labels: enhancement

#51 [OV-43] feat(producer) : 환경 설정
  producer/build.gradle
  producer/src/main/java/com/owlexpress/producer/ProducerApplication.java
  producer/src/main/java/com/owlexpress/producer/common/BaseEntity.java
  producer/src/main/java/com/owlexpress/producer/common/CommonDto.java
  producer/src/main/java/com/owlexpress/producer/common/exception/GlobalExceptionAdvice.java
  producer/src/main/java/com/owlexpress/producer/common/exception/ProducerException.java
  producer/src/main/java/com/owlexpress/producer/infrastructure/config/ProductSearchConfig.java
  producer/src/main/java/com/owlexpress/producer/infrastructure/config/QueryDslConfig.java
Labels: enhancement

#52 Feat(alarm)/create alarm for hub delivery
  ai/src/main/java/com/owl_express/ai/common/util/QueryUtil.java
  alarm/.gitignore
  alarm/build.gradle
  alarm/src/main/resources/application.properties
Labels: chore

#54 [OV-37] refactor(product) : Openfeign, Client Server 연결
  product/build.gradle
  product/src/main/java/com/owlexpress/product/ProductApplication.java
  product/src/main/java/com/owlexpress/product/infrastructure/feignClient/HubClient.java
  product/src/main/java/com/owlexpress/product/infrastructure/feignClient/ProducerClient.java
  product/src/main/java/com/owlexpress/product/presentation/dto/request/CreateProductRequestDto.java
Labels: refactor

#38 [OV-21], [OV-39] Feat(gateway) : JWT 토큰 검증 기능 추가
  gateway/.gitattributes
  gateway/.gitignore
  gateway/build.gradle
  gateway/gradle/wrapper/gradle-wrapper.jar
  gateway/gradle/wrapper/gradle-wrapper.properties
  gateway/gradlew
  gateway/gradlew.bat
  gateway/settings.gradle
  gateway/src/main/java/com/owlexpress/gateway/GatewayApplication.java
  gateway/src/main/java/com/owlexpress/gateway/common/CommonDto.java
  gateway/src/main/java/com/owlexpress/gateway/common/Role.java
  gateway/src/main/java/com/owlexpress/gateway/common/TokenStatus.java
  gateway/src/main/java/com/owlexpress/gateway/common/TokenValidator.java
  gateway/src/main/java/com/owlexpress/gateway/common/advice/GlobalExceptionAdvice.java
  gateway/src/main/java/com/owlexpress/gateway/presentation/JwtAuthorizationFilter.java
  gateway/src/test/java/com/owlexpress/gateway/GatewayApplicationTests.java
Labels: enhancement

#55 Feat(alarm)/create alarm for hub delivery
  alarm/src/main/java/com/owl_express/alarm/application/dtos/CommonDto.java
  alarm/src/main/java/com/owl_express/alarm/application/exceptions/AlarmException.java
  alarm/src/main/java/com/owl_express/alarm/application/service/AlarmService.java
  alarm/src/main/java/com/owl_express/alarm/application/service/AlarmServiceImpl.java
  alarm/src/main/java/com/owl_express/alarm/common/advice/GlobalExceptionAdvice.java
  alarm/src/main/java/com/owl_express/alarm/common/config/JpaConfig.java
  alarm/src/main/java/com/owl_express/alarm/common/config/QueryDslConfig.java
  alarm/src/main/java/com/owl_express/alarm/common/config/WebClientConfig.java
  alarm/src/main/java/com/owl_express/alarm/common/util/CommonUtil.java
  alarm/src/main/java/com/owl_express/alarm/common/util/PageUtil.java
  alarm/src/main/java/com/owl_express/alarm/common/util/QueryUtil.java
  alarm/src/main/java/com/owl_express/alarm/domain/entity/BaseEntity.java
  alarm/src/main/java/com/owl_express/alarm/domain/repository/AlarmRepository.java
  alarm/src/main/java/com/owl_express/alarm/infrastructure/AlarmJpaRepository.java
  alarm/src/main/java/com/owl_express/alarm/infrastructure/AlarmQueryRepository.java
  alarm/src/main/java/com/owl_express/alarm/infrastructure/AlarmQueryRepositoryImpl.java
  alarm/src/main/java/com/owl_express/alarm/infrastructure/AlarmRepositoryImpl.java
  alarm/src/main/java/com/owl_express/alarm/presentation/AlarmController.java
Labels: enhancement

#57 Feat(ai/alarm)/set feignclient
  ai/src/main/java/com/owl_express/ai/AiApplication.java
  alarm/src/main/java/com/owl_express/alarm/AlarmApplication.java
  alarm/src/main/java/com/owl_express/alarm/application/dtos/request/MessageCreateRequestDto.java
  alarm/src/main/java/com/owl_express/alarm/application/dtos/response/MessageCreateResponseDto.java
  alarm/src/main/java/com/owl_express/alarm/infrastructure/feignClient/AiClient.java
  alarm/src/main/java/com/owl_express/alarm/infrastructure/repository/AlarmJpaRepository.java
  alarm/src/main/java/com/owl_express/alarm/infrastructure/repository/AlarmQueryRepository.java
  alarm/src/main/java/com/owl_express/alarm/infrastructure/repository/AlarmQueryRepositoryImpl.java
  alarm/src/main/java/com/owl_express/alarm/infrastructure/repository/AlarmRepositoryImpl.java
Labels: enhancement

#61 Feat(alarm)/create alarm for hub deliver
  alarm/src/main/java/com/owl_express/alarm/application/dtos/request/AlarmCreateRequestDto.java
  alarm/src/main/java/com/owl_express/alarm/application/dtos/request/MessageCreateRequestDto.java
  alarm/src/main/java/com/owl_express/alarm/domain/entity/Notification.java
Labels: enhancement

#63 [OV-61] feat(user): 회원 도메인 추가 (#62)
  user/src/main/java/com/owlexpress/user/common/BaseEntity.java
  user/src/main/java/com/owlexpress/user/domain/constant/ApprovalStatus.java
  user/src/main/java/com/owlexpress/user/domain/constant/PlatformType.java
  user/src/main/java/com/owlexpress/user/domain/constant/Role.java
  user/src/main/java/com/owlexpress/user/domain/entity/User.java
  user/src/test/java/com/owlexpress/user/UserApplicationTests.java
Labels: enhancement

#66 [OV-45] 생성업체 서비스 등록 구현
  producer/build.gradle
  producer/src/main/java/com/owlexpress/producer/application/dto/response/GetHubResponseDto.java
  producer/src/main/java/com/owlexpress/producer/application/dto/response/GetUserResponseDto.java
  producer/src/main/java/com/owlexpress/producer/application/usecase/ProducerUsecase.java
  producer/src/main/java/com/owlexpress/producer/common/CommonDto.java
  producer/src/main/java/com/owlexpress/producer/common/exception/GlobalExceptionAdvice.java
  producer/src/main/java/com/owlexpress/producer/common/util/GeoUtil.java
  producer/src/main/java/com/owlexpress/producer/domain/entity/Producer.java
  producer/src/main/java/com/owlexpress/producer/domain/entity/constant/CompanyType.java
  producer/src/main/java/com/owlexpress/producer/domain/repository/ProducerRepository.java
  producer/src/main/java/com/owlexpress/producer/domain/service/ProducerService.java
  producer/src/main/java/com/owlexpress/producer/domain/service/ProducerServiceImpl.java
  producer/src/main/java/com/owlexpress/producer/infrastructure/feignClient/HubFeignClient.java
  producer/src/main/java/com/owlexpress/producer/infrastructure/feignClient/UserFeignClient.java
  producer/src/main/java/com/owlexpress/producer/infrastructure/repository/ProducerJpaRepository.java
  producer/src/main/java/com/owlexpress/producer/infrastructure/repository/ProducerRepositoryImpl.java
  producer/src/main/java/com/owlexpress/producer/presentation/controller/ProducerController.java
  producer/src/main/java/com/owlexpress/producer/presentation/dto/request/CreateProducerRequestDto.java
Labels: enhancement

#69 Refactor(ai/alarm)/refactor dto
  ai/src/main/java/com/owl_express/ai/application/dtos/response/MessageCreateResponseDto.java
  ai/src/main/java/com/owl_express/ai/application/service/AiServiceImpl.java
  alarm/src/main/java/com/owl_express/alarm/application/dtos/response/MessageCreateResponseDto.java
  alarm/src/main/java/com/owl_express/alarm/application/service/AlarmService.java
  alarm/src/main/java/com/owl_express/alarm/application/service/AlarmServiceImpl.java
  alarm/src/main/java/com/owl_express/alarm/domain/entity/Notification.java
  alarm/src/main/java/com/owl_express/alarm/presentation/AlarmController.java
Labels: refactor

#73 [OV-62] chore(user): 회원 서비스 환경설정 추가 (#65)
  user/build.gradle
  user/src/main/java/com/owlexpress/user/application/exception/PasswordIncorrectException.java
  user/src/main/java/com/owlexpress/user/common/CommonDto.java
  user/src/main/java/com/owlexpress/user/common/exception/GlobalException.java
  user/src/main/java/com/owlexpress/user/infrastructure/config/JpaConfig.java
  user/src/main/java/com/owlexpress/user/infrastructure/config/QueryDslConfig.java
  user/src/main/java/com/owlexpress/user/infrastructure/config/SecurityConfig.java
  user/src/main/java/com/owlexpress/user/infrastructure/exception/UserNotFoundException.java
Labels: chore

#74 [OV-46] Feat(producer) : 생산업체 서비스 수정 기능 구현
  producer/src/main/java/com/owlexpress/producer/application/usecase/ProducerUsecase.java
  producer/src/main/java/com/owlexpress/producer/common/dto/request/CreateProducerRequestDto.java
  producer/src/main/java/com/owlexpress/producer/common/dto/request/UpdateProductRequestDto.java
  producer/src/main/java/com/owlexpress/producer/common/dto/response/GetHubResponseDto.java
  producer/src/main/java/com/owlexpress/producer/common/dto/response/GetUserResponseDto.java
  producer/src/main/java/com/owlexpress/producer/domain/entity/Producer.java
  producer/src/main/java/com/owlexpress/producer/domain/repository/ProducerRepository.java
  producer/src/main/java/com/owlexpress/producer/infrastructure/repository/ProducerRepositoryImpl.java
  producer/src/main/java/com/owlexpress/producer/presentation/controller/ProducerController.java
Labels: enhancement

#76 [OV-64] feat(hub) : 허브 생성 서비스 구현
  hub/build.gradle
  hub/src/main/java/com/owlexpress/hub/common/util/GeoUtil.java
  hub/src/main/java/com/owlexpress/hub/domain/entity/Hub.java
  hub/src/main/java/com/owlexpress/hub/domain/repository/HubRepository.java
  hub/src/main/java/com/owlexpress/hub/domain/service/HubService.java
  hub/src/main/java/com/owlexpress/hub/domain/service/HubServiceImpl.java
  hub/src/main/java/com/owlexpress/hub/infrastructure/HubJpaRepository.java
  hub/src/main/java/com/owlexpress/hub/infrastructure/HubQueryRepository.java
  hub/src/main/java/com/owlexpress/hub/infrastructure/HubQueryRepositoryImpl.java
  hub/src/main/java/com/owlexpress/hub/infrastructure/HubRepositoryImpl.java
  hub/src/main/java/com/owlexpress/hub/presentation/HubController.java
  hub/src/main/java/com/owlexpress/hub/presentation/dto/HubCreateRequestDto.java
Labels: enhancement

#78 [OV-34] feat(user): 회원 Repository 구현 (#77)
  user/src/main/java/com/owlexpress/user/UserApplication.java
  user/src/main/java/com/owlexpress/user/common/exception/AbstractUserUpdateException.java
  user/src/main/java/com/owlexpress/user/common/exception/ExceptionMessage.java
  user/src/main/java/com/owlexpress/user/common/exception/GlobalException.java
  user/src/main/java/com/owlexpress/user/domain/repository/UserRepository.java
  user/src/main/java/com/owlexpress/user/infrastructure/exception/UserNotFoundException.java
  user/src/main/java/com/owlexpress/user/infrastructure/repository/UserJpaRepository.java
  user/src/main/java/com/owlexpress/user/infrastructure/repository/UserQueryDSLImpl.java
  user/src/main/java/com/owlexpress/user/infrastructure/repository/UserQueryDSLRepository.java
  user/src/main/java/com/owlexpress/user/infrastructure/repository/UserRepositoryImpl.java
Labels: enhancement

#80 [OV-47] feat(producer) : 생성업체 서비스 조회 기능 구현
  producer/src/main/java/com/owlexpress/producer/application/usecase/ProducerUsecase.java
  producer/src/main/java/com/owlexpress/producer/common/helper/ProducerHelper.java
  producer/src/main/java/com/owlexpress/producer/domain/service/ProducerService.java
  producer/src/main/java/com/owlexpress/producer/domain/service/ProducerServiceImpl.java
  producer/src/main/java/com/owlexpress/producer/presentation/controller/ProducerController.java
  producer/src/main/java/com/owlexpress/producer/presentation/dto/response/ProducerResponseDto.java
Labels: enhancement

#84 [OV-35] feat(user): 회원 service 구현 (#81)
  user/src/main/java/com/owlexpress/user/application/exception/NewPasswordNotMatchesException.java
  user/src/main/java/com/owlexpress/user/application/service/UserService.java
  user/src/main/java/com/owlexpress/user/application/service/UserServiceImpl.java
  user/src/main/java/com/owlexpress/user/domain/entity/User.java
  user/src/main/java/com/owlexpress/user/presentation/dto/request/UpdatePasswordRequestDto.java
  user/src/main/java/com/owlexpress/user/presentation/dto/request/UpdateUserInfoRequestDto.java
  user/src/main/java/com/owlexpress/user/presentation/dto/request/UserSigninRequestDto.java
  user/src/main/java/com/owlexpress/user/presentation/dto/request/UserSignupRequestDto.java
  user/src/main/java/com/owlexpress/user/presentation/dto/response/GetUserInfoResponseDto.java
  user/src/main/java/com/owlexpress/user/presentation/dto/response/UserSigninResponseDto.java
Labels: enhancement

#82 Feat(alarm)/create alarm for hub deliver
  alarm/build.gradle
  alarm/src/main/java/com/owl_express/alarm/application/dtos/request/AlarmCreateRequestDto.java
  alarm/src/main/java/com/owl_express/alarm/application/dtos/request/MessageCreateRequestDto.java
  alarm/src/main/java/com/owl_express/alarm/application/dtos/response/OrderFindResponseDto.java
  alarm/src/main/java/com/owl_express/alarm/application/exceptions/AlarmException.java
  alarm/src/main/java/com/owl_express/alarm/application/service/AlarmServiceImpl.java
  alarm/src/main/java/com/owl_express/alarm/common/advice/GlobalExceptionAdvice.java
  alarm/src/main/java/com/owl_express/alarm/domain/entity/Notification.java
  alarm/src/main/java/com/owl_express/alarm/domain/repository/AlarmRepository.java
  alarm/src/main/java/com/owl_express/alarm/infrastructure/feignClient/AiClient.java
  alarm/src/main/java/com/owl_express/alarm/infrastructure/feignClient/OrderClient.java
  alarm/src/main/java/com/owl_express/alarm/infrastructure/repository/AlarmJpaRepository.java
  alarm/src/main/java/com/owl_express/alarm/infrastructure/repository/AlarmQueryRepositoryImpl.java
  alarm/src/main/java/com/owl_express/alarm/infrastructure/repository/AlarmRepositoryImpl.java
Labels: enhancement

#87 Refactor(alarm)/refactor log
  alarm/src/main/java/com/owl_express/alarm/application/service/AlarmServiceImpl.java
  alarm/src/main/java/com/owl_express/alarm/common/advice/GlobalExceptionAdvice.java
  alarm/src/main/java/com/owl_express/alarm/infrastructure/feignClient/AiClient.java
  alarm/src/main/java/com/owl_express/alarm/presentation/AlarmController.java
Labels: refactor

#89 [OV-36] feat(user): 회원 controller 구현 (#88)
  user/src/main/java/com/owlexpress/user/presentation/UserController.java
  user/src/main/java/com/owlexpress/user/presentation/dto/ApiResponseMessageConstant.java
Labels: enhancement

#92 [OV-65] feat(hub) : 허브 수정 서비스 구현
  gradlew
  hub/build.gradle
  hub/src/main/java/com/owlexpress/hub/common/BaseEntity.java
  hub/src/main/java/com/owlexpress/hub/common/advice/GlobalExceptionHandler.java
  hub/src/main/java/com/owlexpress/hub/common/exception/HubException.java
  hub/src/main/java/com/owlexpress/hub/domain/entity/Hub.java
  hub/src/main/java/com/owlexpress/hub/domain/repository/HubRepository.java
  hub/src/main/java/com/owlexpress/hub/domain/service/HubService.java
  hub/src/main/java/com/owlexpress/hub/domain/service/HubServiceImpl.java
  hub/src/main/java/com/owlexpress/hub/infrastructure/HubRepositoryImpl.java
  hub/src/main/java/com/owlexpress/hub/presentation/HubController.java
  hub/src/main/java/com/owlexpress/hub/presentation/dto/request/HubCreateRequestDto.java
  hub/src/main/java/com/owlexpress/hub/presentation/dto/request/HubUpdateRequestDto.java
Labels: enhancement, refactor

#94 Feat(alarm)/create alarm for company deliver
  alarm/src/main/java/com/owl_express/alarm/application/dtos/response/AlarmCreateResponseDto.java
  alarm/src/main/java/com/owl_express/alarm/application/exceptions/AlarmException.java
  alarm/src/main/java/com/owl_express/alarm/application/service/AlarmService.java
  alarm/src/main/java/com/owl_express/alarm/application/service/AlarmServiceImpl.java
  alarm/src/main/java/com/owl_express/alarm/common/advice/GlobalExceptionAdvice.java
  alarm/src/main/java/com/owl_express/alarm/common/util/CommonUtil.java
  alarm/src/main/java/com/owl_express/alarm/domain/entity/Notification.java
  alarm/src/main/java/com/owl_express/alarm/infrastructure/feignClient/AiClient.java
  alarm/src/main/java/com/owl_express/alarm/presentation/AlarmController.java
Labels: enhancement

#95 [OV-48] feat(producer) : 생산업체 서비스 삭제 기능 구현
  producer/src/main/java/com/owlexpress/producer/application/usecase/ProducerUsecase.java
  producer/src/main/java/com/owlexpress/producer/domain/entity/Producer.java
  producer/src/main/java/com/owlexpress/producer/infrastructure/feignClient/ProductClient.java
  producer/src/main/java/com/owlexpress/producer/presentation/controller/ProducerController.java
Labels: enhancement

#98 [OV-73]refactor(alarm) : 한국 시간을 기준으로 6시에 발송되도록 수정(#97)
  alarm/src/main/java/com/owl_express/alarm/application/service/AlarmServiceImpl.java
Labels: refactor

#104 Feat(alarm)/delete message
  alarm/src/main/java/com/owl_express/alarm/application/dtos/response/AlarmCreateResponseDto.java
  alarm/src/main/java/com/owl_express/alarm/application/exceptions/AlarmException.java
  alarm/src/main/java/com/owl_express/alarm/application/service/AlarmService.java
  alarm/src/main/java/com/owl_express/alarm/application/service/AlarmServiceImpl.java
  alarm/src/main/java/com/owl_express/alarm/common/advice/GlobalExceptionAdvice.java
  alarm/src/main/java/com/owl_express/alarm/domain/entity/Alarm.java
  alarm/src/main/java/com/owl_express/alarm/domain/repository/AlarmRepository.java
  alarm/src/main/java/com/owl_express/alarm/infrastructure/repository/AlarmJpaRepository.java
  alarm/src/main/java/com/owl_express/alarm/infrastructure/repository/AlarmRepositoryImpl.java
  alarm/src/main/java/com/owl_express/alarm/presentation/AlarmController.java
Labels: enhancement

#103 [OV-84] feat(Product) : 상품 서버와 통신 연결 및 상품 정보 등록 구현
  product/src/main/java/com/owlexpress/product/application/ProductHubUsecase.java
  product/src/main/java/com/owlexpress/product/common/constant/CompanyType.java
  product/src/main/java/com/owlexpress/product/common/dto/CreateProductInfoRequestDto.java
  product/src/main/java/com/owlexpress/product/common/dto/ProducerResponseDto.java
  product/src/main/java/com/owlexpress/product/domain/service/ProductDomainService.java
  product/src/main/java/com/owlexpress/product/domain/service/ProductDomainServiceImpl.java
  product/src/main/java/com/owlexpress/product/infrastructure/feignClient/ProducerClient.java
  product/src/main/java/com/owlexpress/product/presentation/ProductController.java
  product/src/main/java/com/owlexpress/product/presentation/dto/request/CreateProductRequestDto.java
Labels: enhancement

#106 [OV-70] refactor(producer) : dto에 빠진 필드 추가
  producer/src/main/java/com/owlexpress/producer/presentation/controller/ProducerController.java
  producer/src/main/java/com/owlexpress/producer/presentation/dto/response/ProducerResponseDto.java
Labels: enhancement

#108 [OV-71] feat(producer) : producer(productInfo) 서비스 수정 구현
  producer/src/main/java/com/owlexpress/producer/domain/repository/ProductInfoRepository.java
  producer/src/main/java/com/owlexpress/producer/domain/service/ProductInfoService.java
  producer/src/main/java/com/owlexpress/producer/domain/service/ProductInfoServiceImpl.java
  producer/src/main/java/com/owlexpress/producer/infrastructure/repository/productInfo/ProductInfoJpaRepository.java
  producer/src/main/java/com/owlexpress/producer/infrastructure/repository/productInfo/ProductInfoRepositoryImpl.java
  producer/src/main/java/com/owlexpress/producer/presentation/controller/ProductInfoController.java
  producer/src/main/java/com/owlexpress/producer/presentation/dto/request/UpdateProductInfoRequestDto.java
Labels: enhancement

#112 [OV-86] feat(user): master 권한 repository 구현 (#110)
  user/src/main/java/com/owlexpress/user/common/util/PageUtil.java
  user/src/main/java/com/owlexpress/user/common/util/QueryUtil.java
  user/src/main/java/com/owlexpress/user/domain/entity/User.java
  user/src/main/java/com/owlexpress/user/domain/repository/UserRepository.java
  user/src/main/java/com/owlexpress/user/infrastructure/repository/UserQueryDSLImpl.java
  user/src/main/java/com/owlexpress/user/infrastructure/repository/UserQueryDSLRepository.java
  user/src/main/java/com/owlexpress/user/infrastructure/repository/UserRepositoryImpl.java
  user/src/main/java/com/owlexpress/user/presentation/dto/response/GetUsersResponseDto.java
Labels: enhancement

#111 Refactor(alarm)/refactor alarm
  alarm/src/main/java/com/owl_express/alarm/application/dtos/request/AlarmCreateRequestDto.java
  alarm/src/main/java/com/owl_express/alarm/application/dtos/request/MessageCreateRequestDto.java
  alarm/src/main/java/com/owl_express/alarm/application/service/AlarmService.java
  alarm/src/main/java/com/owl_express/alarm/application/service/AlarmServiceImpl.java
  alarm/src/main/java/com/owl_express/alarm/common/advice/GlobalExceptionAdvice.java
  alarm/src/main/java/com/owl_express/alarm/common/exception/ExceptionMessage.java
  alarm/src/main/java/com/owl_express/alarm/domain/entity/Alarm.java
  alarm/src/main/java/com/owl_express/alarm/presentation/AlarmController.java
  alarm/src/main/java/com/owl_express/alarm/presentation/ApiResponseMessageConstant.java
Labels: refactor

#114 Refactor(ai)/refactor ai
  ai/src/main/java/com/owl_express/ai/application/dtos/request/MessageCreateRequestDto.java
  ai/src/main/java/com/owl_express/ai/application/service/AiService.java
  ai/src/main/java/com/owl_express/ai/application/service/AiServiceImpl.java
  ai/src/main/java/com/owl_express/ai/common/advice/GlobalExceptionAdvice.java
  ai/src/main/java/com/owl_express/ai/common/exceptions/ExceptionMessage.java
  ai/src/main/java/com/owl_express/ai/domain/entity/Ai.java
  ai/src/main/java/com/owl_express/ai/presentation/AiController.java
  ai/src/main/java/com/owl_express/ai/presentation/ApiResponseMessageConstant.java
Labels: refactor

#116 [OV-87] 생산업체 상품 정보 수정 기능 구현
  product/src/main/java/com/owlexpress/product/application/ProductHubUsecase.java
  product/src/main/java/com/owlexpress/product/common/dto/UpdateProductInfoRequestDto.java
  product/src/main/java/com/owlexpress/product/domain/service/ProductDomainService.java
  product/src/main/java/com/owlexpress/product/domain/service/ProductDomainServiceImpl.java
  product/src/main/java/com/owlexpress/product/infrastructure/feignClient/ProducerClient.java
  product/src/main/java/com/owlexpress/product/infrastructure/repository/HubInfoJpaRepository.java
  product/src/main/java/com/owlexpress/product/infrastructure/repository/HubInfoRepositoryImpl.java
  product/src/main/java/com/owlexpress/product/presentation/ProductController.java
  product/src/main/java/com/owlexpress/product/presentation/dto/request/UpdateHubInfoRequestDto.java
Labels: enhancement

#118 [OV-16] feat(user): master 권한 service 구현 (#117)
  user/src/main/java/com/owlexpress/user/application/service/MasterService.java
  user/src/main/java/com/owlexpress/user/application/service/MasterServiceImpl.java
  user/src/main/java/com/owlexpress/user/application/service/UserService.java
  user/src/main/java/com/owlexpress/user/application/service/UserServiceImpl.java
  user/src/main/java/com/owlexpress/user/presentation/dto/request/ApprovalUserRequestDto.java
  user/src/main/java/com/owlexpress/user/presentation/dto/request/UpdateUserInfoRequestDto.java
  user/src/main/java/com/owlexpress/user/presentation/dto/request/UpdateUserRoleRequestDto.java
Labels: enhancement

#107 [OV-66], [OV-79] 허브 조회 및 검색 기능 추가(#100)
  hub/src/main/java/com/owlexpress/hub/common/Constant.java
  hub/src/main/java/com/owlexpress/hub/common/HubHelper.java
  hub/src/main/java/com/owlexpress/hub/common/exception/GlobalExceptionHandler.java
  hub/src/main/java/com/owlexpress/hub/common/exception/HubException.java
  hub/src/main/java/com/owlexpress/hub/domain/entity/Hub.java
  hub/src/main/java/com/owlexpress/hub/domain/repository/HubRepository.java
  hub/src/main/java/com/owlexpress/hub/domain/service/HubService.java
  hub/src/main/java/com/owlexpress/hub/domain/service/HubServiceImpl.java
  hub/src/main/java/com/owlexpress/hub/infrastructure/HubQueryRepository.java
  hub/src/main/java/com/owlexpress/hub/infrastructure/HubQueryRepositoryImpl.java
  hub/src/main/java/com/owlexpress/hub/infrastructure/HubRepositoryImpl.java
  hub/src/main/java/com/owlexpress/hub/presentation/HubController.java
  hub/src/main/java/com/owlexpress/hub/presentation/dto/response/HubFindResponseDto.java
  hub/src/main/java/com/owlexpress/hub/presentation/dto/response/HubSearchResponseDto.java
Labels: enhancement

#120 Feat(consumer)/module
  consumer/.gitattributes
  consumer/.gitignore
  consumer/build.gradle
  consumer/gradle/wrapper/gradle-wrapper.jar
  consumer/gradle/wrapper/gradle-wrapper.properties
  consumer/gradlew
  consumer/gradlew.bat
  consumer/settings.gradle
  consumer/src/main/java/com/owlexpress/consumer/ConsumerApplication.java
  consumer/src/test/java/com/owlexpress/consumer/ConsumerApplicationTests.java
  settings.gradle
Labels: enhancement

#123 [OV-68] feat(user): 회원 서비스 Master 권한 Controller 구현 (#122)
  user/src/main/java/com/owlexpress/user/presentation/MasterController.java
  user/src/main/java/com/owlexpress/user/presentation/UserController.java
Labels: enhancement

#124 Feat(alarm)/find alarm
  alarm/src/main/java/com/owl_express/alarm/application/dtos/response/AlarmFindResponseDto.java
  alarm/src/main/java/com/owl_express/alarm/application/service/AlarmService.java
  alarm/src/main/java/com/owl_express/alarm/application/service/AlarmServiceImpl.java
  alarm/src/main/java/com/owl_express/alarm/domain/entity/Alarm.java
  alarm/src/main/java/com/owl_express/alarm/domain/repository/AlarmRepository.java
  alarm/src/main/java/com/owl_express/alarm/infrastructure/repository/AlarmRepositoryImpl.java
  alarm/src/main/java/com/owl_express/alarm/presentation/AlarmController.java
  alarm/src/main/java/com/owl_express/alarm/presentation/ApiResponseMessageConstant.java
Labels: refactor

#129 [OV-92] feat(cart): cart 서비스 모듈 추가 (#126)
  cart/.gitattributes
  cart/.gitignore
  cart/build.gradle
  cart/gradle/wrapper/gradle-wrapper.jar
  cart/gradle/wrapper/gradle-wrapper.properties
  cart/gradlew
  cart/gradlew.bat
  cart/settings.gradle
  cart/src/main/java/com/owlexpress/cart/CartApplication.java
  settings.gradle
Labels: enhancement

#128 [OV-72] feat(producer) : producer(productInfo) 상품 정보 삭제 기능 구현
  producer/src/main/java/com/owlexpress/producer/domain/service/ProductInfoService.java
  producer/src/main/java/com/owlexpress/producer/domain/service/ProductInfoServiceImpl.java
  producer/src/main/java/com/owlexpress/producer/presentation/controller/ProducerController.java
  producer/src/main/java/com/owlexpress/producer/presentation/controller/ProductInfoController.java
Labels: enhancement

#136 [OV-93] feat(cart): 장바구니 서비스 domain 구현 (#130)
  cart/src/main/java/com/owlexpress/cart/common/BaseEntity.java
  cart/src/main/java/com/owlexpress/cart/domain/constant/ProductType.java
  cart/src/main/java/com/owlexpress/cart/domain/entity/Cart.java
  cart/src/main/java/com/owlexpress/cart/domain/entity/CartProduct.java
Labels: enhancement

#138 [OV-97], [OV-98] 허브 상품 엔티티 추가 및 생성 기능 구현
  hub/src/main/java/com/owlexpress/hub/application/HubProductUseCase.java
  hub/src/main/java/com/owlexpress/hub/common/ProductType.java
  hub/src/main/java/com/owlexpress/hub/domain/entity/Hub.java
  hub/src/main/java/com/owlexpress/hub/domain/entity/HubProduct.java
  hub/src/main/java/com/owlexpress/hub/infrastructure/client/ProductClient.java
  hub/src/main/java/com/owlexpress/hub/presentation/HubProductController.java
  hub/src/main/java/com/owlexpress/hub/presentation/dto/request/HubProductCreateRequestDto.java
Labels: enhancement

#135 Feat(alarm)/search alarms
  alarm/src/main/java/com/owl_express/alarm/application/dtos/response/AlarmSearchResponseDto.java
  alarm/src/main/java/com/owl_express/alarm/application/service/AlarmService.java
  alarm/src/main/java/com/owl_express/alarm/application/service/AlarmServiceImpl.java
  alarm/src/main/java/com/owl_express/alarm/common/util/CommonUtil.java
  alarm/src/main/java/com/owl_express/alarm/domain/repository/AlarmRepository.java
  alarm/src/main/java/com/owl_express/alarm/infrastructure/repository/AlarmQueryRepository.java
  alarm/src/main/java/com/owl_express/alarm/infrastructure/repository/AlarmQueryRepositoryImpl.java
  alarm/src/main/java/com/owl_express/alarm/infrastructure/repository/AlarmRepositoryImpl.java
  alarm/src/main/java/com/owl_express/alarm/presentation/AlarmController.java
Labels: enhancement

#140 Chore(delivery)/set module
  delivery/.gitattributes
  delivery/.gitignore
  delivery/build.gradle
  delivery/gradle/wrapper/gradle-wrapper.jar
  delivery/gradle/wrapper/gradle-wrapper.properties
  delivery/gradlew
  delivery/gradlew.bat
  delivery/settings.gradle
  delivery/src/main/java/com/owlexpress/delivery/DeliveryApplication.java
  delivery/src/main/resources/application.properties
  delivery/src/test/java/com/owlexpress/delivery/DeliveryApplicationTests.java
  settings.gradle
Labels: chore

#141 [OV-113] 생산업체 생성시 유저 및 허브 이벤트 연결
  producer/src/main/java/com/owlexpress/producer/application/usecase/ProducerUsecase.java
  producer/src/main/java/com/owlexpress/producer/common/constant/PlatformType.java
  producer/src/main/java/com/owlexpress/producer/common/constant/Role.java
  producer/src/main/java/com/owlexpress/producer/common/dto/request/CreateProducerRequestDto.java
  producer/src/main/java/com/owlexpress/producer/common/dto/response/GetUserInfoResponseDto.java
  producer/src/main/java/com/owlexpress/producer/infrastructure/feignClient/ProductClient.java
  producer/src/main/java/com/owlexpress/producer/infrastructure/feignClient/UserFeignClient.java
Labels: enhancement

#143 [OV-114] feat(consumer) : 수령업체 환경 설정
  consumer/build.gradle
  consumer/src/main/java/com/owlexpress/consumer/ConsumerApplication.java
  consumer/src/main/java/com/owlexpress/consumer/common/BaseEntity.java
  consumer/src/main/java/com/owlexpress/consumer/common/CommonDto.java
  consumer/src/main/java/com/owlexpress/consumer/common/exceptions/ConsumerException.java
  consumer/src/main/java/com/owlexpress/consumer/common/exceptions/ExceptionMessage.java
  consumer/src/main/java/com/owlexpress/consumer/common/exceptions/GlobalExceptionAdvice.java
  consumer/src/main/java/com/owlexpress/consumer/infrastructure/config/ProductSearchConfig.java
  consumer/src/main/java/com/owlexpress/consumer/infrastructure/config/QueryDslConfig.java
  consumer/src/main/java/com/owlexpress/consumer/presentation/controller/ConsumerController.java
  consumer/src/test/java/com/owlexpress/consumer/ConsumerApplicationTests.java
Labels: enhancement

#146 Chore(delivery)set package
  delivery/build.gradle
  delivery/src/main/java/com/owlexpress/delivery/DeliveryApplication.java
  delivery/src/main/java/com/owlexpress/delivery/application/dtos/CommonDto.java
  delivery/src/main/java/com/owlexpress/delivery/application/exceptions/DeliveryException.java
  delivery/src/main/java/com/owlexpress/delivery/application/service/DeliveryService.java
  delivery/src/main/java/com/owlexpress/delivery/application/service/DeliveryServiceImpl.java
  delivery/src/main/java/com/owlexpress/delivery/common/advice/GlobalExceptionAdvice.java
  delivery/src/main/java/com/owlexpress/delivery/common/config/JpaConfig.java
  delivery/src/main/java/com/owlexpress/delivery/common/config/QueryDslConfig.java
  delivery/src/main/java/com/owlexpress/delivery/common/exception/ExceptionMessage.java
  delivery/src/main/java/com/owlexpress/delivery/common/util/CommonUtil.java
  delivery/src/main/java/com/owlexpress/delivery/common/util/PageUtil.java
  delivery/src/main/java/com/owlexpress/delivery/common/util/QueryUtil.java
  delivery/src/main/java/com/owlexpress/delivery/domain/entity/BaseEntity.java
  delivery/src/main/java/com/owlexpress/delivery/domain/entity/Delivery.java
  delivery/src/main/java/com/owlexpress/delivery/domain/repository/DeliveryRepository.java
  delivery/src/main/java/com/owlexpress/delivery/infrastructure/feignClient/AlarmClient.java
  delivery/src/main/java/com/owlexpress/delivery/infrastructure/feignClient/DeliveryManagerClient.java
  delivery/src/main/java/com/owlexpress/delivery/infrastructure/repository/DeliveryJpaRepository.java
  delivery/src/main/java/com/owlexpress/delivery/infrastructure/repository/DeliveryQueryRepository.java
  delivery/src/main/java/com/owlexpress/delivery/infrastructure/repository/DeliveryQueryRepositoryImpl.java
  delivery/src/main/java/com/owlexpress/delivery/infrastructure/repository/DeliveryRepositoryImpl.java
  delivery/src/main/java/com/owlexpress/delivery/presentation/ApiResponseMessageConstant.java
  delivery/src/main/java/com/owlexpress/delivery/presentation/DeliveryController.java
Labels: chore

#147 [OV-115] feat(consumer) : 수령업체 서비스 등록 기능 구현
  consumer/build.gradle
  consumer/src/main/java/com/owlexpress/consumer/application/usecase/ConsumerUsecase.java
  consumer/src/main/java/com/owlexpress/consumer/common/CommonDto.java
  consumer/src/main/java/com/owlexpress/consumer/common/constant/PlatformType.java
  consumer/src/main/java/com/owlexpress/consumer/common/constant/Role.java
  consumer/src/main/java/com/owlexpress/consumer/common/dto/request/CreateConsumerRequestDto.java
  consumer/src/main/java/com/owlexpress/consumer/common/dto/response/GetUserInfoResponseDto.java
  consumer/src/main/java/com/owlexpress/consumer/common/dto/response/HubFindResponseDto.java
  consumer/src/main/java/com/owlexpress/consumer/common/util/GeoUtil.java
  consumer/src/main/java/com/owlexpress/consumer/domain/entity/Consumer.java
  consumer/src/main/java/com/owlexpress/consumer/domain/entity/constant/CompanyType.java
  consumer/src/main/java/com/owlexpress/consumer/domain/repository/ConsumerRepository.java
  consumer/src/main/java/com/owlexpress/consumer/infrastructure/feignClient/HubFeignClient.java
  consumer/src/main/java/com/owlexpress/consumer/infrastructure/feignClient/UserFeignClient.java
  consumer/src/main/java/com/owlexpress/consumer/infrastructure/repository/ConsumerJpaRepository.java
  consumer/src/main/java/com/owlexpress/consumer/infrastructure/repository/ConsumerQueryDslRepository.java
  consumer/src/main/java/com/owlexpress/consumer/infrastructure/repository/ConsumerQueryDslRepositoryImpl.java
  consumer/src/main/java/com/owlexpress/consumer/infrastructure/repository/ConsumerRepositoryImpl.java
  consumer/src/main/java/com/owlexpress/consumer/presentation/controller/ConsumerController.java
  docker-compose.yml
Labels: enhancement

#148 [OV-120] feat(hub) : 허브 상품 조회 기능 추가
  hub/src/main/java/com/owlexpress/hub/domain/repository/HubRepository.java
  hub/src/main/java/com/owlexpress/hub/domain/service/HubService.java
  hub/src/main/java/com/owlexpress/hub/domain/service/HubServiceImpl.java
  hub/src/main/java/com/owlexpress/hub/infrastructure/repository/HubJpaRepository.java
  hub/src/main/java/com/owlexpress/hub/infrastructure/repository/HubQueryRepository.java
  hub/src/main/java/com/owlexpress/hub/infrastructure/repository/HubQueryRepositoryImpl.java
  hub/src/main/java/com/owlexpress/hub/infrastructure/repository/HubRepositoryImpl.java
  hub/src/main/java/com/owlexpress/hub/presentation/HubController.java
  hub/src/main/java/com/owlexpress/hub/presentation/HubProductController.java
  hub/src/main/java/com/owlexpress/hub/presentation/dto/response/HubProductSearchResponseDto.java
Labels: enhancement

#151 [OV-116] feat(consumer) : 수령업체 서비스 수정 기능 구현
  consumer/src/main/java/com/owlexpress/consumer/application/usecase/ConsumerUsecase.java
  consumer/src/main/java/com/owlexpress/consumer/common/dto/request/CreateConsumerRequestDto.java
  consumer/src/main/java/com/owlexpress/consumer/common/dto/request/UpdateConsumerRequestDto.java
  consumer/src/main/java/com/owlexpress/consumer/common/exceptions/ConsumerException.java
  consumer/src/main/java/com/owlexpress/consumer/common/exceptions/GlobalExceptionAdvice.java
  consumer/src/main/java/com/owlexpress/consumer/domain/repository/ConsumerRepository.java
  consumer/src/main/java/com/owlexpress/consumer/infrastructure/repository/ConsumerRepositoryImpl.java
  consumer/src/main/java/com/owlexpress/consumer/presentation/controller/ConsumerController.java
Labels: enhancement

#153 [OV-118] feat(consumer) : 수령업체 서비스 조회 기능 구현
  consumer/src/main/java/com/owlexpress/consumer/domain/service/ConsumerService.java
  consumer/src/main/java/com/owlexpress/consumer/domain/service/ConsumerServiceImpl.java
  consumer/src/main/java/com/owlexpress/consumer/presentation/controller/ConsumerController.java
  consumer/src/main/java/com/owlexpress/consumer/presentation/dto/response/ConsumerResponseDto.java
Labels: enhancement

#154 [OV-121] feat(hub) : 허브 상품 수정
  hub/src/main/java/com/owlexpress/hub/common/Constant.java
  hub/src/main/java/com/owlexpress/hub/common/exception/GlobalExceptionHandler.java
  hub/src/main/java/com/owlexpress/hub/common/exception/HubProductException.java
  hub/src/main/java/com/owlexpress/hub/domain/entity/HubProduct.java
  hub/src/main/java/com/owlexpress/hub/domain/repository/HubRepository.java
  hub/src/main/java/com/owlexpress/hub/domain/service/HubService.java
  hub/src/main/java/com/owlexpress/hub/domain/service/HubServiceImpl.java
  hub/src/main/java/com/owlexpress/hub/infrastructure/repository/HubJpaRepository.java
  hub/src/main/java/com/owlexpress/hub/infrastructure/repository/HubRepositoryImpl.java
  hub/src/main/java/com/owlexpress/hub/presentation/HubProductController.java
  hub/src/main/java/com/owlexpress/hub/presentation/dto/request/HubProductUpdateRequestDto.java
Labels: enhancement

#157 [OV-122] feat(hub) : 허브 상품 단건 조회 기능 추가
  hub/src/main/java/com/owlexpress/hub/domain/service/HubService.java
  hub/src/main/java/com/owlexpress/hub/domain/service/HubServiceImpl.java
  hub/src/main/java/com/owlexpress/hub/presentation/HubProductController.java
  hub/src/main/java/com/owlexpress/hub/presentation/dto/response/HubProductFindResponseDto.java
Labels: enhancement

#156 Feat(delivery)/create entity
  alarm/src/main/java/com/owl_express/alarm/application/service/AlarmServiceImpl.java
  delivery/build.gradle
  delivery/src/main/java/com/owlexpress/delivery/application/exceptions/DeliveryException.java
  delivery/src/main/java/com/owlexpress/delivery/common/advice/GlobalExceptionAdvice.java
  delivery/src/main/java/com/owlexpress/delivery/common/util/GeoUtil.java
  delivery/src/main/java/com/owlexpress/delivery/domain/entity/Delivery.java
  delivery/src/main/java/com/owlexpress/delivery/domain/entity/DeliveryHistory.java
  delivery/src/main/resources/application.properties
Labels: enhancement

#160 [OV-117] 수령업체 서비스 삭제 기능 구현
  consumer/src/main/java/com/owlexpress/consumer/application/usecase/ConsumerUsecase.java
  consumer/src/main/java/com/owlexpress/consumer/common/util/ConsumerHelper.java
  consumer/src/main/java/com/owlexpress/consumer/domain/service/ConsumerServiceImpl.java
  consumer/src/main/java/com/owlexpress/consumer/infrastructure/config/ConsumerSearchConfig.java
  consumer/src/main/java/com/owlexpress/consumer/infrastructure/feignClient/HubFeignClient.java
  consumer/src/main/java/com/owlexpress/consumer/presentation/controller/ConsumerController.java
Labels: enhancement

#163 [OV-132] chore(cart): 장바구니 서비스 설정 변경 (#162)
  cart/build.gradle
  cart/src/main/java/com/owlexpress/cart/common/BaseEntity.java
  cart/src/main/java/com/owlexpress/cart/common/CommonDto.java
  cart/src/main/java/com/owlexpress/cart/domain/constant/ProductType.java
  cart/src/main/java/com/owlexpress/cart/infrastructure/config/JpaConfig.java
Labels: chore

#165 Feat(delivery)/create controller
  delivery/src/main/java/com/owlexpress/delivery/application/dtos/request/DeliveryCreateRequestDto.java
  delivery/src/main/java/com/owlexpress/delivery/application/dtos/request/DeliveryHistoryCreateRequestDto.java
  delivery/src/main/java/com/owlexpress/delivery/application/dtos/response/DeliveryCreateResponseDto.java
  delivery/src/main/java/com/owlexpress/delivery/application/dtos/response/DeliveryFindResponseDto.java
  delivery/src/main/java/com/owlexpress/delivery/application/dtos/response/DeliveryHistoryCreateResponseDto.java
  delivery/src/main/java/com/owlexpress/delivery/domain/entity/Delivery.java
  delivery/src/main/java/com/owlexpress/delivery/presentation/ApiResponseMessageConstant.java
  delivery/src/main/java/com/owlexpress/delivery/presentation/DeliveryController.java
Labels: enhancement

#167 [OV-134] feat(cart): 장바구니 Domain 로직 구현 (#166)
  cart/src/main/java/com/owlexpress/cart/application/exception/CartNotFoundException.java
  cart/src/main/java/com/owlexpress/cart/common/exception/ExceptionMessage.java
  cart/src/main/java/com/owlexpress/cart/common/exception/GlobalException.java
  cart/src/main/java/com/owlexpress/cart/domain/entity/Cart.java
  cart/src/main/java/com/owlexpress/cart/domain/entity/CartProduct.java
  cart/src/main/java/com/owlexpress/cart/domain/exception/CartProductNotFoundException.java
Labels: enhancement

#171 [OV-94] feat(cart): 장바구니 Service 구현 (#131)
  cart/src/main/java/com/owlexpress/cart/application/service/CartService.java
  cart/src/main/java/com/owlexpress/cart/application/service/CartServiceImpl.java
  cart/src/main/java/com/owlexpress/cart/domain/CartRepository.java
  cart/src/main/java/com/owlexpress/cart/infrastructure/repository/CartRepositoryImpl.java
  cart/src/main/java/com/owlexpress/cart/presentation/dto/request/AddCartProductRequestDto.java
  cart/src/main/java/com/owlexpress/cart/presentation/dto/response/CartResponseDto.java
Labels: enhancement

#172 [OV-123] feat(hub) : 허브 상품 삭제 기능 구현
  hub/src/main/java/com/owlexpress/hub/application/HubProductUseCase.java
  hub/src/main/java/com/owlexpress/hub/application/dto/response/OrderSearchResponseDto.java
  hub/src/main/java/com/owlexpress/hub/domain/entity/HubProduct.java
  hub/src/main/java/com/owlexpress/hub/domain/service/HubServiceImpl.java
  hub/src/main/java/com/owlexpress/hub/infrastructure/client/OrderClient.java
  hub/src/main/java/com/owlexpress/hub/presentation/HubProductController.java
  hub/src/main/java/com/owlexpress/hub/presentation/dto/request/HubProductCreateRequestDto.java
Labels: enhancement

#176 [OV-140] chore(payment) : 결제 모듈 추가
  payment/.gitattributes
  payment/.gitignore
  payment/build.gradle
  payment/gradle/wrapper/gradle-wrapper.jar
  payment/gradle/wrapper/gradle-wrapper.properties
  payment/gradlew
  payment/gradlew.bat
  payment/src/main/java/com/owlexpress/payment/PaymentApplication.java
  payment/src/main/java/com/owlexpress/payment/common/BaseEntity.java
  payment/src/main/java/com/owlexpress/payment/common/ResponseMessage.java
  payment/src/main/java/com/owlexpress/payment/common/config/JpaConfig.java
  payment/src/main/java/com/owlexpress/payment/common/config/QueryDslConfig.java
  payment/src/main/java/com/owlexpress/payment/common/exception/GlobalExceptionHandler.java
  payment/src/main/java/com/owlexpress/payment/common/exception/PaymentException.java
  payment/src/main/java/com/owlexpress/payment/presentation/dto/CommonDto.java
  settings.gradle
Labels: chore

#179 [OV-133] feat(order): 주문 서비스 모듈 생성 (#178)
  order/.gitattributes
  order/.gitignore
  order/build.gradle
  order/gradle/wrapper/gradle-wrapper.jar
  order/gradle/wrapper/gradle-wrapper.properties
  order/gradlew
  order/gradlew.bat
  order/settings.gradle
  order/src/main/java/com/owlexpress/order/OrderApplication.java
  order/src/main/java/com/owlexpress/order/common/CommonDto.java
  order/src/main/java/com/owlexpress/order/common/entity/BaseEntity.java
  order/src/main/java/com/owlexpress/order/common/exception/ExceptionMessage.java
  order/src/main/java/com/owlexpress/order/common/exception/GlobalException.java
  order/src/main/java/com/owlexpress/order/common/util/PageUtil.java
  order/src/main/java/com/owlexpress/order/common/util/QueryUtil.java
  order/src/main/java/com/owlexpress/order/infrastructure/config/JpaConfig.java
  order/src/main/java/com/owlexpress/order/infrastructure/config/QueryDslConfig.java
  order/src/main/java/com/owlexpress/order/presentation/dto/ApiResponseMessageConstant.java
  settings.gradle
Labels: enhancement

#180 [OV-145] chore(payment) : 결제 엔티티 및 리포지토리 추가
  payment/src/main/java/com/owlexpress/payment/domain/constant/PaymentStatus.java
  payment/src/main/java/com/owlexpress/payment/domain/entity/Payment.java
  payment/src/main/java/com/owlexpress/payment/domain/repository/PaymentRepository.java
  payment/src/main/java/com/owlexpress/payment/infrastructure/repository/PaymentJpaRepository.java
  payment/src/main/java/com/owlexpress/payment/infrastructure/repository/PaymentQueryRepository.java
  payment/src/main/java/com/owlexpress/payment/infrastructure/repository/PaymentQueryRepositoryImpl.java
  payment/src/main/java/com/owlexpress/payment/infrastructure/repository/PaymentRepositoryImpl.java
Labels: chore

#183 [OV-138] feat(order): 주문 domain 구현 (#182)
  order/src/main/java/com/owlexpress/order/domain/constant/OrderStatus.java
  order/src/main/java/com/owlexpress/order/domain/constant/OrderType.java
  order/src/main/java/com/owlexpress/order/domain/constant/ProductType.java
  order/src/main/java/com/owlexpress/order/domain/entity/Order.java
  order/src/main/java/com/owlexpress/order/domain/entity/OrderProduct.java
Labels: enhancement

#189 [OV-130] Interval 변환 기능 구현
  hub/src/main/java/com/owlexpress/hub/application/HubDistanceService.java
  hub/src/main/java/com/owlexpress/hub/domain/entity/HubIntervalInfo.java
  hub/src/main/java/com/owlexpress/hub/domain/repository/HubIntervalInfoRepository.java
  hub/src/main/java/com/owlexpress/hub/infrastructure/repository/HubIntervalInfoJpaRepository.java
  hub/src/main/java/com/owlexpress/hub/infrastructure/repository/HubIntervalInfoRepositoryImpl.java
Labels: refactor

#188 [OV-141] feat(payment) : 결제 생성 기능 추가
  payment/build.gradle
  payment/src/main/java/com/owlexpress/payment/application/PaymentUseCase.java
  payment/src/main/java/com/owlexpress/payment/common/config/WebClientConfig.java
  payment/src/main/java/com/owlexpress/payment/domain/entity/Payment.java
  payment/src/main/java/com/owlexpress/payment/domain/repository/PaymentRepository.java
  payment/src/main/java/com/owlexpress/payment/infrastructure/repository/PaymentRepositoryImpl.java
  payment/src/main/java/com/owlexpress/payment/presentation/PaymentController.java
  payment/src/main/java/com/owlexpress/payment/presentation/dto/request/PaymentCreateRequestDto.java
Labels: enhancement

#190 [OV-142] feat(payment) : 결제 취소 기능 추가
  payment/src/main/java/com/owlexpress/payment/application/PaymentUseCase.java
  payment/src/main/java/com/owlexpress/payment/domain/entity/Payment.java
  payment/src/main/java/com/owlexpress/payment/domain/repository/PaymentRepository.java
  payment/src/main/java/com/owlexpress/payment/infrastructure/repository/PaymentJpaRepository.java
  payment/src/main/java/com/owlexpress/payment/infrastructure/repository/PaymentRepositoryImpl.java
  payment/src/main/java/com/owlexpress/payment/presentation/PaymentController.java
  payment/src/main/java/com/owlexpress/payment/presentation/dto/request/PaymentCreateRequestDto.java
  payment/src/main/java/com/owlexpress/payment/presentation/dto/request/PaymentDeleteRequestDto.java
Labels: enhancement

#192 Feat(payment)/implement payment search
  payment/src/main/java/com/owlexpress/payment/application/PaymentUseCase.java
  payment/src/main/java/com/owlexpress/payment/application/dto/response/OrderFindResponseDto.java
  payment/src/main/java/com/owlexpress/payment/application/dto/response/PaymentFindResponseDto.java
  payment/src/main/java/com/owlexpress/payment/common/exception/GlobalExceptionHandler.java
  payment/src/main/java/com/owlexpress/payment/common/exception/PaymentException.java
  payment/src/main/java/com/owlexpress/payment/domain/entity/Payment.java
  payment/src/main/java/com/owlexpress/payment/domain/repository/PaymentRepository.java
  payment/src/main/java/com/owlexpress/payment/infrastructure/client/OrderClient.java
  payment/src/main/java/com/owlexpress/payment/infrastructure/repository/PaymentJpaRepository.java
  payment/src/main/java/com/owlexpress/payment/infrastructure/repository/PaymentRepositoryImpl.java
  payment/src/main/java/com/owlexpress/payment/presentation/PaymentController.java
Labels: enhancement

#194 [OV-149] feat(gateway) : 권한에 따른 인가 처리 추가
  gateway/build.gradle
  gateway/settings.gradle
  gateway/src/main/java/com/owlexpress/gateway/common/Role.java
  gateway/src/main/java/com/owlexpress/gateway/common/config/SecurityConfig.java
  settings.gradle
Labels: enhancement

#200 [OV-151] feat(order): 주문 서비스 domain 로직 구현 (#196)
  order/src/main/java/com/owlexpress/order/domain/entity/Order.java
  order/src/main/java/com/owlexpress/order/domain/entity/OrderProduct.java
Labels: enhancement

#201 Feat(hub interval info)/best rout
  hub/src/main/java/com/owlexpress/hub/application/HubDistanceInitializer.java
  hub/src/main/java/com/owlexpress/hub/application/HubDistanceService.java
  hub/src/main/java/com/owlexpress/hub/application/HubPathFinder.java
  hub/src/main/java/com/owlexpress/hub/application/HubProductUseCase.java
  hub/src/main/java/com/owlexpress/hub/application/dto/request/DirectionsRequestDto.java
  hub/src/main/java/com/owlexpress/hub/application/dto/response/HubIntervalInfoDto.java
  hub/src/main/java/com/owlexpress/hub/application/dto/response/OrderSearchResponseDto.java
  hub/src/main/java/com/owlexpress/hub/common/BaseEntity.java
  hub/src/main/java/com/owlexpress/hub/common/Constant.java
  hub/src/main/java/com/owlexpress/hub/common/HubHelper.java
  hub/src/main/java/com/owlexpress/hub/common/converter/DurationConverter.java
  hub/src/main/java/com/owlexpress/hub/common/dto/response/RouteResponseDto.java
  hub/src/main/java/com/owlexpress/hub/common/exception/HubException.java
  hub/src/main/java/com/owlexpress/hub/domain/entity/HubIntervalInfo.java
  hub/src/main/java/com/owlexpress/hub/domain/entity/HubProduct.java
  hub/src/main/java/com/owlexpress/hub/domain/repository/HubIntervalInfoRepository.java
  hub/src/main/java/com/owlexpress/hub/domain/repository/HubRepository.java
  hub/src/main/java/com/owlexpress/hub/domain/service/HubService.java
  hub/src/main/java/com/owlexpress/hub/domain/service/HubServiceImpl.java
  hub/src/main/java/com/owlexpress/hub/infrastructure/client/OrderClient.java
  hub/src/main/java/com/owlexpress/hub/infrastructure/repository/HubIntervalInfoJpaRepository.java
  hub/src/main/java/com/owlexpress/hub/infrastructure/repository/HubIntervalInfoRepositoryImpl.java
  hub/src/main/java/com/owlexpress/hub/infrastructure/repository/HubJpaRepository.java
  hub/src/main/java/com/owlexpress/hub/infrastructure/repository/HubQueryRepositoryImpl.java
  hub/src/main/java/com/owlexpress/hub/infrastructure/repository/HubRepositoryImpl.java
  hub/src/main/java/com/owlexpress/hub/presentation/HubController.java
  hub/src/main/java/com/owlexpress/hub/presentation/HubIntervalInfoController.java
  hub/src/main/java/com/owlexpress/hub/presentation/HubProductController.java
  hub/src/main/java/com/owlexpress/hub/presentation/dto/request/HubCreateRequestDto.java
  hub/src/main/java/com/owlexpress/hub/presentation/dto/request/HubProductCreateRequestDto.java
  hub/src/main/java/com/owlexpress/hub/presentation/dto/request/HubProductUpdateRequestDto.java
  hub/src/main/java/com/owlexpress/hub/presentation/dto/request/HubUpdateRequestDto.java
  hub/src/main/java/com/owlexpress/hub/presentation/dto/request/RouteRequestDto.java
  hub/src/main/java/com/owlexpress/hub/presentation/dto/response/HubFindResponseDto.java
  hub/src/main/java/com/owlexpress/hub/presentation/dto/response/HubIntervalInfoResponse.java
  hub/src/main/java/com/owlexpress/hub/presentation/dto/response/HubProductFindResponseDto.java
  hub/src/main/java/com/owlexpress/hub/presentation/dto/response/HubProductSearchResponseDto.java
  hub/src/main/java/com/owlexpress/hub/presentation/dto/response/HubSearchResponseDto.java
  hub/src/main/resources/data.sql
Labels: enhancement

#206 Refactor(producer)/feign client
  producer/src/main/java/com/owlexpress/producer/application/dto/request/UpdateProductDto.java
  producer/src/main/java/com/owlexpress/producer/application/usecase/ProducerUsecase.java
  producer/src/main/java/com/owlexpress/producer/common/dto/request/UpdateProducerRequestDto.java
  producer/src/main/java/com/owlexpress/producer/common/exception/BadRequestFeignExceptionHandler.java
  producer/src/main/java/com/owlexpress/producer/common/exception/ExceptionMessage.java
  producer/src/main/java/com/owlexpress/producer/common/exception/FeignExceptionHandlerStrategy.java
  producer/src/main/java/com/owlexpress/producer/common/exception/GlobalExceptionAdvice.java
  producer/src/main/java/com/owlexpress/producer/common/exception/NotFoundFeignExceptionHandler.java
  producer/src/main/java/com/owlexpress/producer/common/exception/ProducerException.java
  producer/src/main/java/com/owlexpress/producer/common/exception/ServerErrorFeignExceptionHandler.java
  producer/src/main/java/com/owlexpress/producer/common/helper/ProducerHelper.java
  producer/src/main/java/com/owlexpress/producer/infrastructure/feignClient/HubProductClient.java
  producer/src/main/java/com/owlexpress/producer/infrastructure/feignClient/ProductClient.java
  producer/src/main/java/com/owlexpress/producer/presentation/controller/ProducerController.java
Labels: refactor

#205 [OV-146] refactor(hubIntervalInfo) : 요일 처리 0하나 빠짐 추가
  hub/src/main/java/com/owlexpress/hub/infrastructure/repository/HubIntervalInfoJpaRepository.java
Labels: refactor

#204 Feat(delivery)/set repository
  ai/src/main/java/com/owl_express/ai/common/util/PageUtil.java
  alarm/src/main/java/com/owl_express/alarm/common/util/PageUtil.java
  alarm/src/main/java/com/owl_express/alarm/infrastructure/repository/AlarmQueryRepositoryImpl.java
  delivery/build.gradle
  delivery/src/main/java/com/owlexpress/delivery/application/dtos/request/DeliveryCreateRequestDto.java
  delivery/src/main/java/com/owlexpress/delivery/application/dtos/request/DeliveryManagerRequestDto.java
  delivery/src/main/java/com/owlexpress/delivery/application/dtos/response/DeliveryFindResponseDto.java
  delivery/src/main/java/com/owlexpress/delivery/application/exceptions/DeliveryException.java
  delivery/src/main/java/com/owlexpress/delivery/application/service/DeliveryServiceImpl.java
  delivery/src/main/java/com/owlexpress/delivery/common/advice/GlobalExceptionAdvice.java
  delivery/src/main/java/com/owlexpress/delivery/common/converter/IntervalConverter.java
  delivery/src/main/java/com/owlexpress/delivery/common/util/PageUtil.java
  delivery/src/main/java/com/owlexpress/delivery/domain/entity/Delivery.java
  delivery/src/main/java/com/owlexpress/delivery/domain/entity/DeliveryHistory.java
  delivery/src/main/java/com/owlexpress/delivery/domain/repository/DeliveryRepository.java
  delivery/src/main/java/com/owlexpress/delivery/infrastructure/repository/DeliveryQueryRepository.java
  delivery/src/main/java/com/owlexpress/delivery/infrastructure/repository/DeliveryQueryRepositoryImpl.java
  delivery/src/main/java/com/owlexpress/delivery/infrastructure/repository/DeliveryRepositoryImpl.java
Labels: enhancement

#207 [OV-146] 응답값 수정, JsonIgnore 추가
  hub/src/main/java/com/owlexpress/hub/common/dto/response/RouteResponseDto.java
  hub/src/main/java/com/owlexpress/hub/presentation/HubIntervalInfoController.java
Labels: refactor

#208 [OV-153] feat(order): 주문 서비스 service 구현 (#198)
  order/src/main/java/com/owlexpress/order/application/exception/OrderNotFoundException.java
  order/src/main/java/com/owlexpress/order/application/service/OrderService.java
  order/src/main/java/com/owlexpress/order/application/service/OrderServiceImpl.java
  order/src/main/java/com/owlexpress/order/common/exception/ExceptionMessage.java
  order/src/main/java/com/owlexpress/order/common/exception/GlobalException.java
  order/src/main/java/com/owlexpress/order/infrastructure/client/PaymentFeignClient.java
  order/src/main/java/com/owlexpress/order/presentation/dto/request/CreateOrderProductRequestDto.java
  order/src/main/java/com/owlexpress/order/presentation/dto/request/CreateOrderRequestDto.java
  order/src/main/java/com/owlexpress/order/presentation/dto/request/UpdateOrderRequestDto.java
  order/src/main/java/com/owlexpress/order/presentation/dto/request/UpdateOrderStatusRequestDto.java
  order/src/main/java/com/owlexpress/order/presentation/dto/response/CreateOrderResponseDto.java
  order/src/main/java/com/owlexpress/order/presentation/dto/response/GetOrderResponseDto.java
Labels: enhancement

#209 [OV-154] feat(order): 주문 서비스 controller 구현 (#199)
  order/src/main/java/com/owlexpress/order/presentation/controller/OrderController.java
  order/src/main/java/com/owlexpress/order/presentation/dto/ApiResponseMessageConstant.java
Labels: enhancement

#215 [OV-157] refactor(gateway) : reactive security authenticationManager 추가
  gateway/src/main/java/com/owlexpress/gateway/common/config/SecurityConfig.java
  gateway/src/main/java/com/owlexpress/gateway/common/security/JwtAuthenticationManager.java
  gateway/src/main/java/com/owlexpress/gateway/common/security/JwtServerAuthenticationConverter.java
  gateway/src/main/java/com/owlexpress/gateway/presentation/JwtAuthorizationFilter.java
Labels: refactor

#213 Feat(delivery)/create additional dto
  delivery/src/main/java/com/owlexpress/delivery/application/dtos/request/DeliveryCompleteRequestDto.java
  delivery/src/main/java/com/owlexpress/delivery/application/dtos/request/DeliveryManagerRequestDto.java
  delivery/src/main/java/com/owlexpress/delivery/application/service/DeliveryService.java
  delivery/src/main/java/com/owlexpress/delivery/application/service/DeliveryServiceImpl.java
  delivery/src/main/java/com/owlexpress/delivery/domain/entity/Delivery.java
  delivery/src/main/java/com/owlexpress/delivery/domain/entity/DeliveryHistory.java
  delivery/src/main/java/com/owlexpress/delivery/presentation/DeliveryController.java
Labels: enhancement

#221 Feat(delivery manager)/module
  DeliveryManager/.gitattributes
  DeliveryManager/.gitignore
  DeliveryManager/build.gradle
  DeliveryManager/gradle/wrapper/gradle-wrapper.jar
  DeliveryManager/gradle/wrapper/gradle-wrapper.properties
  DeliveryManager/gradlew
  DeliveryManager/gradlew.bat
  DeliveryManager/settings.gradle
  DeliveryManager/src/main/java/com/owlexpress/deliverymanager/DeliveryManagerApplication.java
  settings.gradle
Labels: enhancement

#222 [OV-161] feat(gateway) : Passport헤더 발급 필터 추가
  gateway/src/main/java/com/owlexpress/gateway/common/Passport.java
  gateway/src/main/java/com/owlexpress/gateway/common/TokenValidator.java
  gateway/src/main/java/com/owlexpress/gateway/common/filter/AddPassportHeaderGatewayFilter.java
  gateway/src/main/java/com/owlexpress/gateway/common/security/JwtAuthenticationManager.java
Labels: enhancement

#224 Feat(delivery manager)/global setting
  deliveryManager/.gitattributes
  deliveryManager/.gitignore
  deliveryManager/build.gradle
  deliveryManager/gradle/wrapper/gradle-wrapper.jar
  deliveryManager/gradle/wrapper/gradle-wrapper.properties
  deliveryManager/gradlew
  deliveryManager/gradlew.bat
  deliveryManager/settings.gradle
  deliveryManager/src/main/java/com/owlexpress/deliverymanager/DeliveryManagerApplication.java
  deliveryManager/src/main/java/com/owlexpress/deliverymanager/application/usecase/ConsumerDeliveryManagerUsecase.java
  deliveryManager/src/main/java/com/owlexpress/deliverymanager/application/usecase/HubDeliveryManagerUsecase.java
  deliveryManager/src/main/java/com/owlexpress/deliverymanager/common/exception/BadRequestFeignExceptionHandler.java
  deliveryManager/src/main/java/com/owlexpress/deliverymanager/common/exception/ConsumerDeliveryManagerException.java
  deliveryManager/src/main/java/com/owlexpress/deliverymanager/common/exception/ExceptionMessage.java
  deliveryManager/src/main/java/com/owlexpress/deliverymanager/common/exception/FeignExceptionHandlerStrategy.java
  deliveryManager/src/main/java/com/owlexpress/deliverymanager/common/exception/GlobalExceptionAdvice.java
  deliveryManager/src/main/java/com/owlexpress/deliverymanager/common/exception/HubDeliveryManagerException.java
  deliveryManager/src/main/java/com/owlexpress/deliverymanager/common/exception/NotFoundFeignExceptionHandler.java
  deliveryManager/src/main/java/com/owlexpress/deliverymanager/common/exception/ServerErrorFeignExceptionHandler.java
  deliveryManager/src/main/java/com/owlexpress/deliverymanager/domain/repository/ConsumerDeliveryManagerRepository.java
  deliveryManager/src/main/java/com/owlexpress/deliverymanager/domain/repository/HubDeliveryManagerRepository.java
  deliveryManager/src/main/java/com/owlexpress/deliverymanager/infrastructure/BaseEntity.java
  deliveryManager/src/main/java/com/owlexpress/deliverymanager/infrastructure/CommonDto.java
  deliveryManager/src/main/java/com/owlexpress/deliverymanager/infrastructure/config/ProductSearchConfig.java
  deliveryManager/src/main/java/com/owlexpress/deliverymanager/infrastructure/config/QueryDslConfig.java
  deliveryManager/src/main/java/com/owlexpress/deliverymanager/presentation/controller/ConsumerDeliveryManagerController.java
  deliveryManager/src/main/java/com/owlexpress/deliverymanager/presentation/controller/HubDeliveryManagerController.java
  deliveryManager/src/main/java/com/owlexpress/deliverymanager/presentation/dto/request/CreateConsumerDeliveryManagerRequestDto.java
  deliveryManager/src/main/java/com/owlexpress/deliverymanager/presentation/dto/request/CreateHubDeliveryManagerRequestDto.java
  deliveryManager/src/main/java/com/owlexpress/deliverymanager/presentation/dto/request/UpdateConsumerDeliveryManagerRequestDto.java
  deliveryManager/src/main/java/com/owlexpress/deliverymanager/presentation/dto/request/UpdateHubDeliveryManagerRequestDto.java
  deliveryManager/src/main/java/com/owlexpress/deliverymanager/presentation/dto/response/FindConsumerResponseDto.java
  deliveryManager/src/main/java/com/owlexpress/deliverymanager/presentation/dto/response/FindHubDeliveryResponseDto.java
Labels: enhancement

#226 Refactor(ai)/refactor dto and message
  ai/src/main/java/com/owl_express/ai/application/dtos/request/CompanyDeliverMessageCreateRequestDto.java
  ai/src/main/java/com/owl_express/ai/application/dtos/request/HubDeliverMessageCreateRequestDto.java
  ai/src/main/java/com/owl_express/ai/application/dtos/request/MessageCreateRequestDto.java
  ai/src/main/java/com/owl_express/ai/application/service/AiService.java
  ai/src/main/java/com/owl_express/ai/application/service/AiServiceImpl.java
  ai/src/main/java/com/owl_express/ai/presentation/AiController.java
Labels: refactor

#227 [OV-167] feat(hubProduct) : 허브 상품별 재고 확보 여부 기능 추가
  hub/src/main/java/com/owlexpress/hub/application/dto/response/HubProductIsEnoughResponseDto.java
  hub/src/main/java/com/owlexpress/hub/application/dto/response/HubProductStockResponseDto.java
  hub/src/main/java/com/owlexpress/hub/common/Constant.java
  hub/src/main/java/com/owlexpress/hub/domain/repository/HubRepository.java
  hub/src/main/java/com/owlexpress/hub/domain/service/HubService.java
  hub/src/main/java/com/owlexpress/hub/domain/service/HubServiceImpl.java
  hub/src/main/java/com/owlexpress/hub/infrastructure/repository/HubJpaRepository.java
  hub/src/main/java/com/owlexpress/hub/infrastructure/repository/HubRepositoryImpl.java
  hub/src/main/java/com/owlexpress/hub/presentation/HubProductController.java
  hub/src/main/java/com/owlexpress/hub/presentation/dto/request/HubProductCheckRequestDto.java
Labels: enhancement

#229 Feat(delivery manager)/create update delete
  deliveryManager/src/main/java/com/owlexpress/deliverymanager/application/usecase/ConsumerDeliveryManagerUsecase.java
  deliveryManager/src/main/java/com/owlexpress/deliverymanager/application/usecase/HubDeliveryManagerUsecase.java
  deliveryManager/src/main/java/com/owlexpress/deliverymanager/common/exception/ConsumerDeliveryManagerException.java
  deliveryManager/src/main/java/com/owlexpress/deliverymanager/common/exception/ExceptionMessage.java
  deliveryManager/src/main/java/com/owlexpress/deliverymanager/common/exception/GlobalExceptionAdvice.java
  deliveryManager/src/main/java/com/owlexpress/deliverymanager/common/exception/HubDeliveryManagerException.java
  deliveryManager/src/main/java/com/owlexpress/deliverymanager/domain/PlatformType.java
  deliveryManager/src/main/java/com/owlexpress/deliverymanager/domain/dto/response/HubFindResponseDto.java
  deliveryManager/src/main/java/com/owlexpress/deliverymanager/domain/entity/ConsumerDeliveryManager.java
  deliveryManager/src/main/java/com/owlexpress/deliverymanager/domain/entity/HubDeliveryManager.java
  deliveryManager/src/main/java/com/owlexpress/deliverymanager/domain/repository/ConsumerDeliveryManagerRepository.java
  deliveryManager/src/main/java/com/owlexpress/deliverymanager/domain/repository/HubDeliveryManagerRepository.java
  deliveryManager/src/main/java/com/owlexpress/deliverymanager/infrastructure/feignClient/HubClient.java
  deliveryManager/src/main/java/com/owlexpress/deliverymanager/infrastructure/repository/consumer/ConsumerDeliveryManagerJpaRepository.java
  deliveryManager/src/main/java/com/owlexpress/deliverymanager/infrastructure/repository/consumer/ConsumerDeliveryManagerQueryDslRepository.java
  deliveryManager/src/main/java/com/owlexpress/deliverymanager/infrastructure/repository/consumer/ConsumerDeliveryManagerQueryDslRepositoryImpl.java
  deliveryManager/src/main/java/com/owlexpress/deliverymanager/infrastructure/repository/consumer/ConsumerDeliveryManagerRepositoryImpl.java
  deliveryManager/src/main/java/com/owlexpress/deliverymanager/infrastructure/repository/hub/HubDeliveryManagerJpaRepository.java
  deliveryManager/src/main/java/com/owlexpress/deliverymanager/infrastructure/repository/hub/HubDeliveryManagerQueryDslRepository.java
  deliveryManager/src/main/java/com/owlexpress/deliverymanager/infrastructure/repository/hub/HubDeliveryManagerQueryDslRepositoryImpl.java
  deliveryManager/src/main/java/com/owlexpress/deliverymanager/infrastructure/repository/hub/HubDeliveryManagerRepositoryImpl.java
  deliveryManager/src/main/java/com/owlexpress/deliverymanager/presentation/controller/ConsumerDeliveryManagerController.java
  deliveryManager/src/main/java/com/owlexpress/deliverymanager/presentation/controller/HubDeliveryManagerController.java
  deliveryManager/src/main/java/com/owlexpress/deliverymanager/presentation/dto/request/CreateConsumerDeliveryManagerRequestDto.java
  deliveryManager/src/main/java/com/owlexpress/deliverymanager/presentation/dto/request/CreateHubDeliveryManagerRequestDto.java
  deliveryManager/src/main/java/com/owlexpress/deliverymanager/presentation/dto/request/UpdateConsumerDeliveryManagerRequestDto.java
  deliveryManager/src/main/java/com/owlexpress/deliverymanager/presentation/dto/request/UpdateHubDeliveryManagerRequestDto.java
Labels: enhancement

#231 [OV-168] feat(deliveryManager) : 조회/검색 기능 구현
  deliveryManager/src/main/java/com/owlexpress/deliverymanager/application/usecase/ConsumerDeliveryManagerUsecase.java
  deliveryManager/src/main/java/com/owlexpress/deliverymanager/application/usecase/HubDeliveryManagerUsecase.java
  deliveryManager/src/main/java/com/owlexpress/deliverymanager/common/exception/GlobalExceptionAdvice.java
  deliveryManager/src/main/java/com/owlexpress/deliverymanager/domain/repository/ConsumerDeliveryManagerRepository.java
  deliveryManager/src/main/java/com/owlexpress/deliverymanager/domain/repository/HubDeliveryManagerRepository.java
  deliveryManager/src/main/java/com/owlexpress/deliverymanager/infrastructure/config/DeliveryManagerSearchConfig.java
  deliveryManager/src/main/java/com/owlexpress/deliverymanager/infrastructure/repository/consumer/ConsumerDeliveryManagerQueryDslRepository.java
  deliveryManager/src/main/java/com/owlexpress/deliverymanager/infrastructure/repository/consumer/ConsumerDeliveryManagerQueryDslRepositoryImpl.java
  deliveryManager/src/main/java/com/owlexpress/deliverymanager/infrastructure/repository/consumer/ConsumerDeliveryManagerRepositoryImpl.java
  deliveryManager/src/main/java/com/owlexpress/deliverymanager/infrastructure/repository/hub/HubDeliveryManagerQueryDslRepository.java
  deliveryManager/src/main/java/com/owlexpress/deliverymanager/infrastructure/repository/hub/HubDeliveryManagerQueryDslRepositoryImpl.java
  deliveryManager/src/main/java/com/owlexpress/deliverymanager/infrastructure/repository/hub/HubDeliveryManagerRepositoryImpl.java
  deliveryManager/src/main/java/com/owlexpress/deliverymanager/presentation/controller/ConsumerDeliveryManagerController.java
  deliveryManager/src/main/java/com/owlexpress/deliverymanager/presentation/controller/HubDeliveryManagerController.java
  deliveryManager/src/main/java/com/owlexpress/deliverymanager/presentation/dto/request/CreateConsumerDeliveryManagerRequestDto.java
  deliveryManager/src/main/java/com/owlexpress/deliverymanager/presentation/dto/response/FindConsumerResponseDto.java
  deliveryManager/src/main/java/com/owlexpress/deliverymanager/presentation/dto/response/FindHubDeliveryResponseDto.java
Labels: enhancement

#232 [OV-169] : fix(gateway) : auth 경로에 대해 인증 없이도 사용할 수 있도록 수정
  gateway/src/main/java/com/owlexpress/gateway/common/filter/AddPassportHeaderGatewayFilter.java
Labels: bug

#233 [OV-168] refactor(deliveryManager) : 생성 및 수정에 허브 상태 검사 로직 추가
  deliveryManager/src/main/java/com/owlexpress/deliverymanager/application/usecase/ConsumerDeliveryManagerUsecase.java
  deliveryManager/src/main/java/com/owlexpress/deliverymanager/application/usecase/HubDeliveryManagerUsecase.java
  deliveryManager/src/main/java/com/owlexpress/deliverymanager/common/exception/ConsumerDeliveryManagerException.java
  deliveryManager/src/main/java/com/owlexpress/deliverymanager/common/exception/ExceptionMessage.java
  deliveryManager/src/main/java/com/owlexpress/deliverymanager/common/exception/HubDeliveryManagerException.java
  deliveryManager/src/main/java/com/owlexpress/deliverymanager/domain/repository/ConsumerDeliveryManagerRepository.java
  deliveryManager/src/main/java/com/owlexpress/deliverymanager/domain/repository/HubDeliveryManagerRepository.java
  deliveryManager/src/main/java/com/owlexpress/deliverymanager/infrastructure/repository/consumer/ConsumerDeliveryManagerJpaRepository.java
  deliveryManager/src/main/java/com/owlexpress/deliverymanager/infrastructure/repository/consumer/ConsumerDeliveryManagerRepositoryImpl.java
  deliveryManager/src/main/java/com/owlexpress/deliverymanager/infrastructure/repository/hub/HubDeliveryManagerJpaRepository.java
  deliveryManager/src/main/java/com/owlexpress/deliverymanager/infrastructure/repository/hub/HubDeliveryManagerQueryDslRepository.java
  deliveryManager/src/main/java/com/owlexpress/deliverymanager/infrastructure/repository/hub/HubDeliveryManagerRepositoryImpl.java
  deliveryManager/src/main/java/com/owlexpress/deliverymanager/presentation/controller/ConsumerDeliveryManagerController.java
  deliveryManager/src/main/java/com/owlexpress/deliverymanager/presentation/dto/request/CreateConsumerDeliveryManagerRequestDto.java
  deliveryManager/src/main/java/com/owlexpress/deliverymanager/presentation/dto/request/CreateHubDeliveryManagerRequestDto.java
Labels: refactor

#237 Feat(alarm)/set feignclient
  ai/src/main/java/com/owl_express/ai/application/dtos/request/CompanyDeliverMessageCreateRequestDto.java
  ai/src/main/java/com/owl_express/ai/application/dtos/request/HubDeliverMessageCreateRequestDto.java
  alarm/src/main/java/com/owl_express/alarm/application/dtos/request/AlarmCreateRequestDto.java
  alarm/src/main/java/com/owl_express/alarm/application/dtos/request/CompanyDeliverMessageCreateRequestDto.java
  alarm/src/main/java/com/owl_express/alarm/application/dtos/request/HubDeliverMessageCreateRequestDto.java
  alarm/src/main/java/com/owl_express/alarm/application/exceptions/AlarmException.java
  alarm/src/main/java/com/owl_express/alarm/application/exceptions/BadRequestFeignExceptionHandler.java
  alarm/src/main/java/com/owl_express/alarm/application/exceptions/FeignExceptionHandlerStrategy.java
  alarm/src/main/java/com/owl_express/alarm/application/exceptions/NotFoundFeignExceptionHandler.java
  alarm/src/main/java/com/owl_express/alarm/application/exceptions/ServerErrorFeignExceptionHandler.java
  alarm/src/main/java/com/owl_express/alarm/application/service/AlarmServiceImpl.java
  alarm/src/main/java/com/owl_express/alarm/application/service/AlarmUsecase.java
  alarm/src/main/java/com/owl_express/alarm/common/advice/GlobalExceptionAdvice.java
  delivery/src/main/java/com/owlexpress/delivery/application/dtos/request/DeliveryCreateRequestDto.java
Labels: refactor

#240 [OV-171] refactor(user): 회원 서비스 refactor (#238)
  user/src/main/java/com/owlexpress/user/application/service/MasterService.java
  user/src/main/java/com/owlexpress/user/application/service/MasterServiceImpl.java
  user/src/main/java/com/owlexpress/user/application/service/UserService.java
  user/src/main/java/com/owlexpress/user/application/service/UserServiceImpl.java
  user/src/main/java/com/owlexpress/user/common/PassportHelper.java
  user/src/main/java/com/owlexpress/user/common/util/PageUtil.java
  user/src/main/java/com/owlexpress/user/presentation/MasterController.java
  user/src/main/java/com/owlexpress/user/presentation/UserController.java
  user/src/main/java/com/owlexpress/user/presentation/dto/ApiResponseMessageConstant.java
  user/src/main/java/com/owlexpress/user/presentation/dto/request/ApprovalUserRequestDto.java
  user/src/main/java/com/owlexpress/user/presentation/dto/request/UpdatePasswordRequestDto.java
  user/src/main/java/com/owlexpress/user/presentation/dto/request/UpdateUserInfoRequestDto.java
  user/src/main/java/com/owlexpress/user/presentation/dto/request/UpdateUserRoleRequestDto.java
  user/src/main/java/com/owlexpress/user/presentation/dto/request/UserSigninRequestDto.java
  user/src/main/java/com/owlexpress/user/presentation/dto/request/UserSignupRequestDto.java
  user/src/main/java/com/owlexpress/user/presentation/dto/response/UserSigninResponseDto.java
  user/src/main/resources/application-prod.yml
  user/src/main/resources/application.yml
Labels: refactor

#239 [OV-172] refactor(gateway) : FeignClient 연동 부분 수정
  auth/src/main/java/com/owlexpress/auth/application/AuthServiceImpl.java
  auth/src/main/java/com/owlexpress/auth/application/dto/request/UserLoginRequestDto.java
  auth/src/main/java/com/owlexpress/auth/common/BadRequestFeignExceptionHandler.java
  auth/src/main/java/com/owlexpress/auth/common/FeignExceptionHandlerStrategy.java
  auth/src/main/java/com/owlexpress/auth/common/NotFoundFeignExceptionHandler.java
  auth/src/main/java/com/owlexpress/auth/common/ServerErrorFeignExceptionHandler.java
  auth/src/main/java/com/owlexpress/auth/infrastructure/UserClient.java
  auth/src/main/java/com/owlexpress/auth/presentation/AuthController.java
  auth/src/main/java/com/owlexpress/auth/presentation/dto/CommonDto.java
  auth/src/main/java/com/owlexpress/auth/presentation/dto/request/LoginRequestDto.java
  gateway/src/main/java/com/owlexpress/gateway/common/filter/AddPassportHeaderGatewayFilter.java
Labels: enhancement

#243 [OV-173] refactor(producer) : passport 추가, 예외 해결
  producer/src/main/java/com/owlexpress/producer/application/usecase/ProducerUsecase.java
  producer/src/main/java/com/owlexpress/producer/common/dto/response/PassportDto.java
  producer/src/main/java/com/owlexpress/producer/common/helper/PassportHelper.java
  producer/src/main/java/com/owlexpress/producer/domain/service/ProductInfoService.java
  producer/src/main/java/com/owlexpress/producer/domain/service/ProductInfoServiceImpl.java
  producer/src/main/java/com/owlexpress/producer/infrastructure/feignClient/HubFeignClient.java
  producer/src/main/java/com/owlexpress/producer/infrastructure/feignClient/UserFeignClient.java
  producer/src/main/java/com/owlexpress/producer/presentation/controller/ProducerController.java
  producer/src/main/java/com/owlexpress/producer/presentation/controller/ProductInfoController.java
Labels: refactor

#244 Feat(ai/delivery/alarm)/set passport
  ai/src/main/java/com/owl_express/ai/application/service/AiService.java
  ai/src/main/java/com/owl_express/ai/application/service/AiServiceImpl.java
  ai/src/main/java/com/owl_express/ai/common/dto/PassportDto.java
  ai/src/main/java/com/owl_express/ai/common/helper/PassportHelper.java
  ai/src/main/java/com/owl_express/ai/presentation/AiController.java
  alarm/src/main/java/com/owl_express/alarm/application/service/AlarmService.java
  alarm/src/main/java/com/owl_express/alarm/application/service/AlarmServiceImpl.java
  alarm/src/main/java/com/owl_express/alarm/common/dto/PassportDto.java
  alarm/src/main/java/com/owl_express/alarm/common/helper/PassportHelper.java
  alarm/src/main/java/com/owl_express/alarm/presentation/AlarmController.java
  delivery/src/main/java/com/owlexpress/delivery/application/service/DeliveryService.java
  delivery/src/main/java/com/owlexpress/delivery/application/service/DeliveryServiceImpl.java
  delivery/src/main/java/com/owlexpress/delivery/common/dto/PassportDto.java
  delivery/src/main/java/com/owlexpress/delivery/common/helper/PassportHelper.java
  delivery/src/main/java/com/owlexpress/delivery/presentation/DeliveryController.java
  user/.gitignore
Labels: refactor

#248 [OV-179] refactor(hub) : 허브 상품 아이디 조회 API 추가 및 리팩토링
  hub/src/main/java/com/owlexpress/hub/application/HubProductUseCase.java
  hub/src/main/java/com/owlexpress/hub/application/dto/response/OrderSearchResponseDto.java
  hub/src/main/java/com/owlexpress/hub/common/constant/ProductType.java
  hub/src/main/java/com/owlexpress/hub/common/constant/Role.java
  hub/src/main/java/com/owlexpress/hub/common/dto/response/PassportDto.java
  hub/src/main/java/com/owlexpress/hub/common/exception/HubException.java
  hub/src/main/java/com/owlexpress/hub/common/helper/HubHelper.java
  hub/src/main/java/com/owlexpress/hub/common/helper/PassportHelper.java
  hub/src/main/java/com/owlexpress/hub/domain/entity/HubProduct.java
  hub/src/main/java/com/owlexpress/hub/domain/repository/HubProductRepository.java
  hub/src/main/java/com/owlexpress/hub/domain/repository/HubRepository.java
  hub/src/main/java/com/owlexpress/hub/domain/service/HubProductService.java
  hub/src/main/java/com/owlexpress/hub/domain/service/HubProductServiceImpl.java
  hub/src/main/java/com/owlexpress/hub/domain/service/HubService.java
  hub/src/main/java/com/owlexpress/hub/domain/service/HubServiceImpl.java
  hub/src/main/java/com/owlexpress/hub/infrastructure/repository/hub/HubJpaRepository.java
  hub/src/main/java/com/owlexpress/hub/infrastructure/repository/hub/HubQueryRepository.java
  hub/src/main/java/com/owlexpress/hub/infrastructure/repository/hub/HubQueryRepositoryImpl.java
  hub/src/main/java/com/owlexpress/hub/infrastructure/repository/hub/HubRepositoryImpl.java
  hub/src/main/java/com/owlexpress/hub/infrastructure/repository/hubIntervalInfo/HubIntervalInfoJpaRepository.java
  hub/src/main/java/com/owlexpress/hub/infrastructure/repository/hubIntervalInfo/HubIntervalInfoRepositoryImpl.java
  hub/src/main/java/com/owlexpress/hub/infrastructure/repository/hubProduct/HubProductJpaRepository.java
  hub/src/main/java/com/owlexpress/hub/infrastructure/repository/hubProduct/HubProductRepositoryImpl.java
  hub/src/main/java/com/owlexpress/hub/presentation/HubController.java
  hub/src/main/java/com/owlexpress/hub/presentation/HubProductController.java
  hub/src/main/java/com/owlexpress/hub/presentation/dto/request/HubProductCreateRequestDto.java
  hub/src/main/java/com/owlexpress/hub/presentation/dto/request/HubProductUpdateRequestDto.java
  hub/src/main/java/com/owlexpress/hub/presentation/dto/response/HubProductFindResponseDto.java
  hub/src/main/java/com/owlexpress/hub/presentation/dto/response/HubProductSearchResponseDto.java
Labels: enhancement, refactor

#253 Feat(ai/alarm)/connect feign
  ai/src/main/java/com/owl_express/ai/application/service/AiService.java
  ai/src/main/java/com/owl_express/ai/application/service/AiServiceImpl.java
  ai/src/main/java/com/owl_express/ai/common/advice/GlobalExceptionAdvice.java
  ai/src/main/java/com/owl_express/ai/presentation/AiController.java
  ai/src/main/java/com/owl_express/ai/presentation/ApiResponseMessageConstant.java
  alarm/src/main/java/com/owl_express/alarm/application/service/AlarmServiceImpl.java
  alarm/src/main/java/com/owl_express/alarm/application/service/AlarmUsecase.java
  alarm/src/main/java/com/owl_express/alarm/common/advice/GlobalExceptionAdvice.java
  alarm/src/main/java/com/owl_express/alarm/infrastructure/feignClient/AiClient.java
  delivery/src/main/java/com/owlexpress/delivery/application/dtos/response/AlarmCreateResponseDto.java
  delivery/src/main/java/com/owlexpress/delivery/application/exceptions/BadRequestFeignExceptionHandler.java
  delivery/src/main/java/com/owlexpress/delivery/application/exceptions/DeliveryException.java
  delivery/src/main/java/com/owlexpress/delivery/application/exceptions/FeignExceptionHandlerStrategy.java
  delivery/src/main/java/com/owlexpress/delivery/application/exceptions/NotFoundFeignExceptionHandler.java
  delivery/src/main/java/com/owlexpress/delivery/application/exceptions/ServerErrorFeignExceptionHandler.java
  delivery/src/main/java/com/owlexpress/delivery/application/service/DeliveryServiceImpl.java
  delivery/src/main/java/com/owlexpress/delivery/application/service/DeliveryUsecase.java
  delivery/src/main/java/com/owlexpress/delivery/common/advice/GlobalExceptionAdvice.java
  delivery/src/main/java/com/owlexpress/delivery/common/exception/ExceptionMessage.java
  delivery/src/main/java/com/owlexpress/delivery/domain/entity/Delivery.java
  delivery/src/main/java/com/owlexpress/delivery/domain/entity/DeliveryHistory.java
  delivery/src/main/java/com/owlexpress/delivery/infrastructure/feignClient/AlarmClient.java
  delivery/src/main/java/com/owlexpress/delivery/infrastructure/feignClient/DeliveryManagerClient.java
  delivery/src/main/java/com/owlexpress/delivery/infrastructure/feignClient/OrderClient.java
Labels: enhancement, refactor

#254 [OV-179] feat(hub) : 허브상품 재고 확정 기능 추가 1/3
  hub/src/main/java/com/owlexpress/hub/application/HubProductUseCase.java
  hub/src/main/java/com/owlexpress/hub/application/dto/response/HubProductInfoResponseDto.java
  hub/src/main/java/com/owlexpress/hub/domain/repository/HubRepository.java
  hub/src/main/java/com/owlexpress/hub/infrastructure/repository/hub/HubQueryRepository.java
  hub/src/main/java/com/owlexpress/hub/infrastructure/repository/hub/HubQueryRepositoryImpl.java
  hub/src/main/java/com/owlexpress/hub/infrastructure/repository/hub/HubRepositoryImpl.java
  hub/src/main/java/com/owlexpress/hub/presentation/HubProductController.java
  hub/src/main/java/com/owlexpress/hub/presentation/dto/request/OrderConfirmRequestDto.java
Labels: refactor

#256 [OV-179] feat(hub) : 상품들 받아서 재고 확정하는 기능 추가 2/3
  hub/src/main/java/com/owlexpress/hub/application/HubProductUseCase.java
  hub/src/main/java/com/owlexpress/hub/application/dto/response/HubProductInfoResponseDto.java
  hub/src/main/java/com/owlexpress/hub/infrastructure/repository/hub/HubQueryRepository.java
  hub/src/main/java/com/owlexpress/hub/infrastructure/repository/hub/HubQueryRepositoryImpl.java
  hub/src/main/java/com/owlexpress/hub/infrastructure/repository/hub/HubRepositoryImpl.java
Labels: enhancement

#257 [OV-173]refactor(product) : 생산업체 리팩토링
  product/src/main/java/com/owlexpress/product/application/ProductUsecase.java
  product/src/main/java/com/owlexpress/product/common/constant/Role.java
  product/src/main/java/com/owlexpress/product/common/dto/request/CreateProductInfoRequestDto.java
  product/src/main/java/com/owlexpress/product/common/dto/request/HubProductCreateRequestDto.java
  product/src/main/java/com/owlexpress/product/common/dto/request/HubProductUpdateRequestDto.java
  product/src/main/java/com/owlexpress/product/common/dto/request/UpdateProductInfoRequestDto.java
  product/src/main/java/com/owlexpress/product/common/dto/response/HubProductFindResponseDto.java
  product/src/main/java/com/owlexpress/product/common/dto/response/PassportDto.java
  product/src/main/java/com/owlexpress/product/common/dto/response/ProducerResponseDto.java
  product/src/main/java/com/owlexpress/product/common/helper/PassportHelper.java
  product/src/main/java/com/owlexpress/product/domain/service/HubInfoService.java
  product/src/main/java/com/owlexpress/product/domain/service/HubInfoServiceImpl.java
  product/src/main/java/com/owlexpress/product/infrastructure/feignClient/CartClient.java
  product/src/main/java/com/owlexpress/product/infrastructure/feignClient/HubClient.java
  product/src/main/java/com/owlexpress/product/infrastructure/feignClient/ProducerClient.java
  product/src/main/java/com/owlexpress/product/presentation/HubInfoController.java
  product/src/main/java/com/owlexpress/product/presentation/ProductController.java
  product/src/main/java/com/owlexpress/product/presentation/dto/request/CreateProductRequestDto.java
  product/src/main/java/com/owlexpress/product/presentation/dto/request/UpdateProductDto.java
Labels: enhancement

#262 [OV-184] feat(cart): 주문 서비스 feign client 구현 (#261)
  order/src/main/java/com/owlexpress/order/OrderApplication.java
  order/src/main/java/com/owlexpress/order/application/dto/request/CreatePaymentRequestDto.java
  order/src/main/java/com/owlexpress/order/application/dto/request/HubProductIsEnoughRequestDto.java
  order/src/main/java/com/owlexpress/order/application/dto/response/GetConsumerInfoResponseDto.java
  order/src/main/java/com/owlexpress/order/application/dto/response/HubProductIsEnoughResponseDto.java
  order/src/main/java/com/owlexpress/order/application/service/OrderService.java
  order/src/main/java/com/owlexpress/order/application/service/OrderServiceImpl.java
  order/src/main/java/com/owlexpress/order/common/constant/CompanyType.java
  order/src/main/java/com/owlexpress/order/common/constant/Role.java
  order/src/main/java/com/owlexpress/order/common/dto/CommonDto.java
  order/src/main/java/com/owlexpress/order/common/dto/PassportDto.java
  order/src/main/java/com/owlexpress/order/common/exception/BadRequestFeignExceptionHandler.java
  order/src/main/java/com/owlexpress/order/common/exception/FeignExceptionHandlerStrategy.java
  order/src/main/java/com/owlexpress/order/common/exception/GlobalException.java
  order/src/main/java/com/owlexpress/order/common/exception/NotFoundFeignExceptionHandler.java
  order/src/main/java/com/owlexpress/order/common/exception/ServerErrorFeignExceptionHandler.java
  order/src/main/java/com/owlexpress/order/common/helper/PassportHelper.java
  order/src/main/java/com/owlexpress/order/infrastructure/client/CartFeignClient.java
  order/src/main/java/com/owlexpress/order/infrastructure/client/ConsumerFeignClient.java
  order/src/main/java/com/owlexpress/order/infrastructure/client/PaymentFeignClient.java
  order/src/main/java/com/owlexpress/order/infrastructure/config/RedisConfig.java
  order/src/main/java/com/owlexpress/order/presentation/controller/OrderController.java
  order/src/main/java/com/owlexpress/order/presentation/dto/request/CreateOrderRequestDto.java
Labels: enhancement

#265 [OV-186] feat(producer) : zipkin, redis 추가
  producer/build.gradle
  producer/src/main/java/com/owlexpress/producer/infrastructure/config/RedisConfig.java
Labels: enhancement

#268 Refactor(product)/fallback
  product/build.gradle
  product/src/main/java/com/owlexpress/product/application/ProductUsecase.java
  product/src/main/java/com/owlexpress/product/common/exceptions/GlobalExceptionAdvice.java
  product/src/main/java/com/owlexpress/product/common/exceptions/ProductException.java
  product/src/main/java/com/owlexpress/product/infrastructure/config/RedisConfig.java
  product/src/main/java/com/owlexpress/product/presentation/ProductController.java
  user/src/main/resources/application.yml
Labels: enhancement

#260 Feat(delivery)/set fallback
  delivery/src/main/java/com/owlexpress/delivery/application/exceptions/DeliveryException.java
  delivery/src/main/java/com/owlexpress/delivery/application/service/DeliveryServiceImpl.java
  delivery/src/main/java/com/owlexpress/delivery/common/advice/GlobalExceptionAdvice.java
  delivery/src/main/java/com/owlexpress/delivery/common/exception/ExceptionMessage.java
Labels: enhancement

#266 [OV-186] feat(producer) : zipkin, redis, redisson 추가
  hub/build.gradle
  hub/src/main/java/com/owlexpress/hub/infrastructure/config/RedisConfig.java
Labels: enhancement

#269 Feat(delivery)/set redis zipkin
  delivery/build.gradle
Labels: chore

#272 [OV-190] feat(user): 회원 서비스 passport 적용 (#271)
  .gitignore
  user/src/main/java/com/owlexpress/user/application/service/MasterServiceImpl.java
  user/src/main/java/com/owlexpress/user/application/service/UserServiceImpl.java
  user/src/main/java/com/owlexpress/user/common/PassportHelper.java
  user/src/main/java/com/owlexpress/user/common/dto/PassportDto.java
  user/src/main/java/com/owlexpress/user/common/helper/PassportHelper.java
  user/src/main/java/com/owlexpress/user/presentation/UserController.java
  user/src/main/resources/application-dev.yml
  user/src/main/resources/application-test.yml
Labels: enhancement

#274 [OV-191] refactor(consumer) : 생성/수정/조회 리팩터링
  consumer/src/main/java/com/owlexpress/consumer/application/usecase/ConsumerUsecase.java
  consumer/src/main/java/com/owlexpress/consumer/common/dto/request/CreateConsumerRequestDto.java
  consumer/src/main/java/com/owlexpress/consumer/common/dto/response/PassportDto.java
  consumer/src/main/java/com/owlexpress/consumer/common/helper/PassportHelper.java
  consumer/src/main/java/com/owlexpress/consumer/infrastructure/feignClient/UserFeignClient.java
  consumer/src/main/java/com/owlexpress/consumer/presentation/controller/ConsumerController.java
  hub/src/main/java/com/owlexpress/hub/presentation/HubController.java
  hub/src/main/java/com/owlexpress/hub/presentation/dto/response/HubFindResponseDto.java
  producer/src/main/java/com/owlexpress/producer/application/usecase/ProducerUsecase.java
  producer/src/main/java/com/owlexpress/producer/infrastructure/feignClient/UserFeignClient.java
Labels: refactor

#276 Feat(alarm)/set fallback message
  alarm/build.gradle
  alarm/src/main/java/com/owl_express/alarm/application/dtos/request/HubDeliverFallbackMessageCreateRequestDto.java
  alarm/src/main/java/com/owl_express/alarm/application/service/AlarmService.java
  alarm/src/main/java/com/owl_express/alarm/application/service/AlarmServiceImpl.java
  alarm/src/main/java/com/owl_express/alarm/domain/entity/Alarm.java
  alarm/src/main/java/com/owl_express/alarm/presentation/AlarmController.java
  alarm/src/main/java/com/owl_express/alarm/presentation/ApiResponseMessageConstant.java
Labels: enhancement

#277 [OV-193] feat(Delivery) : 주문중인 수령업체 기록 조회 API개발
  delivery/src/main/java/com/owlexpress/delivery/application/service/DeliveryService.java
  delivery/src/main/java/com/owlexpress/delivery/application/service/DeliveryServiceImpl.java
  delivery/src/main/java/com/owlexpress/delivery/domain/repository/DeliveryRepository.java
  delivery/src/main/java/com/owlexpress/delivery/infrastructure/repository/DeliveryJpaRepository.java
  delivery/src/main/java/com/owlexpress/delivery/infrastructure/repository/DeliveryRepositoryImpl.java
  delivery/src/main/java/com/owlexpress/delivery/presentation/DeliveryController.java
Labels: enhancement

#279 [OV-194] refactor(cart): 장바구니 서비스 삭제 리팩토링 (#278)
  cart/src/main/java/com/owlexpress/cart/application/service/CartService.java
  cart/src/main/java/com/owlexpress/cart/application/service/CartServiceImpl.java
  cart/src/main/java/com/owlexpress/cart/presentation/CartController.java
Labels: refactor

#275 [OV-192] feat(hubProduct) : 재고 확정 기능 추가
  hub/src/main/java/com/owlexpress/hub/application/HubProductUseCase.java
  hub/src/main/java/com/owlexpress/hub/application/dto/response/HubProductInfoResponseDto.java
  hub/src/main/java/com/owlexpress/hub/common/Constant.java
  hub/src/main/java/com/owlexpress/hub/common/exception/HubProductException.java
  hub/src/main/java/com/owlexpress/hub/domain/entity/HubProduct.java
  hub/src/main/java/com/owlexpress/hub/domain/repository/HubProductRepository.java
  hub/src/main/java/com/owlexpress/hub/infrastructure/repository/hub/HubQueryRepository.java
  hub/src/main/java/com/owlexpress/hub/infrastructure/repository/hub/HubQueryRepositoryImpl.java
  hub/src/main/java/com/owlexpress/hub/infrastructure/repository/hubProduct/HubProductJpaRepository.java
  hub/src/main/java/com/owlexpress/hub/infrastructure/repository/hubProduct/HubProductRepositoryImpl.java
  hub/src/main/java/com/owlexpress/hub/presentation/HubProductController.java
  hub/src/main/java/com/owlexpress/hub/presentation/dto/response/HubProductOrderConfirmResponseDto.java
Labels: enhancement

#281 [OV-189] feat(alarm) : 알람 찾아오는 기준 변경(#280)
  alarm/src/main/java/com/owl_express/alarm/application/service/AlarmService.java
  alarm/src/main/java/com/owl_express/alarm/application/service/AlarmServiceImpl.java
  alarm/src/main/java/com/owl_express/alarm/domain/repository/AlarmRepository.java
  alarm/src/main/java/com/owl_express/alarm/infrastructure/repository/AlarmJpaRepository.java
  alarm/src/main/java/com/owl_express/alarm/infrastructure/repository/AlarmRepositoryImpl.java
  alarm/src/main/java/com/owl_express/alarm/presentation/AlarmController.java
Labels: refactor

#283 [OV-195] bug(cart): 장바구니 서비스 삭제 API 경로 중복 문제 (#282)
  cart/src/main/java/com/owlexpress/cart/presentation/CartController.java
Labels: bug

#291 Refactor(alarm)/refactor dto
  alarm/src/main/java/com/owl_express/alarm/application/dtos/response/AlarmCreateResponseDto.java
Labels: refactor

#293 [OV-201] fix(delivery) : orderType 오탈자 수정 (#292)
  delivery/src/main/java/com/owlexpress/delivery/domain/entity/Delivery.java
Labels: refactor

#285 [OV-196] refactor(consumer) : 수령업체 삭제
  consumer/src/main/java/com/owlexpress/consumer/application/usecase/ConsumerUsecase.java
  consumer/src/main/java/com/owlexpress/consumer/common/exceptions/ConsumerException.java
  consumer/src/main/java/com/owlexpress/consumer/common/exceptions/ExceptionMessage.java
  consumer/src/main/java/com/owlexpress/consumer/common/exceptions/GlobalExceptionAdvice.java
  consumer/src/main/java/com/owlexpress/consumer/infrastructure/feignClient/CartClient.java
  consumer/src/main/java/com/owlexpress/consumer/infrastructure/feignClient/DeliveryClient.java
  consumer/src/main/java/com/owlexpress/consumer/presentation/controller/ConsumerController.java
Labels: refactor

#296 Refactor(delivery)/refactor create delivery
  delivery/src/main/java/com/owlexpress/delivery/application/service/DeliveryServiceImpl.java
Labels: refactor

#298 refactor(hub) : hubName 반환하도록 수정
  hub/src/main/java/com/owlexpress/hub/application/HubProductUseCase.java
  hub/src/main/java/com/owlexpress/hub/application/dto/response/HubProductInfoResponseDto.java
  hub/src/main/java/com/owlexpress/hub/infrastructure/repository/hub/HubQueryRepositoryImpl.java
  hub/src/main/java/com/owlexpress/hub/presentation/dto/response/HubProductOrderConfirmResponseDto.java
Labels: refactor

#303 Refactor(alarm)/refactor response
  ai/build.gradle
  alarm/src/main/java/com/owl_express/alarm/presentation/AlarmController.java
Labels: refactor

#305 [OV-183] refactor(deliveryManager) : 배송담당자 client 연결
  deliveryManager/data.sql
  deliveryManager/src/main/java/com/owlexpress/deliverymanager/application/dto/response/AlarmCreateResponseDto.java
  deliveryManager/src/main/java/com/owlexpress/deliverymanager/application/usecase/ConsumerDeliveryManagerUsecase.java
  deliveryManager/src/main/java/com/owlexpress/deliverymanager/application/usecase/HubDeliveryManagerUsecase.java
  deliveryManager/src/main/java/com/owlexpress/deliverymanager/common/dto/request/AlarmCreateRequestDto.java
  deliveryManager/src/main/java/com/owlexpress/deliverymanager/common/dto/response/PassportDto.java
  deliveryManager/src/main/java/com/owlexpress/deliverymanager/common/helper/PassportHelper.java
  deliveryManager/src/main/java/com/owlexpress/deliverymanager/domain/entity/ConsumerDeliveryManager.java
  deliveryManager/src/main/java/com/owlexpress/deliverymanager/domain/entity/HubDeliveryManager.java
  deliveryManager/src/main/java/com/owlexpress/deliverymanager/infrastructure/feignClient/AlarmClient.java
  deliveryManager/src/main/java/com/owlexpress/deliverymanager/presentation/controller/ConsumerDeliveryManagerController.java
  deliveryManager/src/main/java/com/owlexpress/deliverymanager/presentation/controller/HubDeliveryManagerController.java
  deliveryManager/src/main/java/com/owlexpress/deliverymanager/presentation/dto/request/CreateConsumerDeliveryManagerRequestDto.java
  deliveryManager/src/main/java/com/owlexpress/deliverymanager/presentation/dto/request/CreateHubDeliveryManagerRequestDto.java
  deliveryManager/src/main/java/com/owlexpress/deliverymanager/presentation/dto/response/FindConsumerResponseDto.java
  deliveryManager/src/main/java/com/owlexpress/deliverymanager/presentation/dto/response/FindHubDeliveryResponseDto.java
Labels: enhancement, refactor

#306 chore(payment) : zipkin + redis 의존성 추가
  payment/build.gradle
Labels: chore

#307 Feat(delivery)/connect feign client
  delivery/src/main/java/com/owlexpress/delivery/application/dtos/response/DeliveryCreateResponseDto.java
  delivery/src/main/java/com/owlexpress/delivery/application/service/DeliveryService.java
  delivery/src/main/java/com/owlexpress/delivery/application/service/DeliveryServiceImpl.java
  delivery/src/main/java/com/owlexpress/delivery/application/service/DeliveryUsecase.java
  delivery/src/main/java/com/owlexpress/delivery/infrastructure/feignClient/DeliveryManagerClient.java
  delivery/src/main/java/com/owlexpress/delivery/presentation/DeliveryController.java
Labels: refactor

#308 Refactor(payment)/add delivery
  payment/src/main/java/com/owlexpress/payment/application/PaymentUseCase.java
  payment/src/main/java/com/owlexpress/payment/infrastructure/client/DeliveryClient.java
  payment/src/main/java/com/owlexpress/payment/presentation/PaymentController.java
Labels: enhancement

#310 [OV-206] feat(order): 주문 서비스 결제 생성 응답값 적용 (#309)
  order/src/main/java/com/owlexpress/order/application/dto/response/CreatePaymentResponseDto.java
  order/src/main/java/com/owlexpress/order/application/service/OrderServiceImpl.java
  order/src/main/java/com/owlexpress/order/domain/entity/Order.java
  order/src/main/java/com/owlexpress/order/infrastructure/client/PaymentFeignClient.java
  order/src/main/java/com/owlexpress/order/presentation/dto/request/CreateOrderRequestDto.java
Labels: enhancement

#312 [OV-186] chore(user): 회원 서비스 의존성 추가(#264)
  user/build.gradle
Labels: chore

#311 [OV-186] chore(order): 주문 서비스 zipkin, redis추가 (#264)
  order/build.gradle
  order/src/main/java/com/owlexpress/order/infrastructure/config/RedisConfig.java
Labels: chore

#315 Refactor(delivery)/refactor create delivery history
  delivery/src/main/java/com/owlexpress/delivery/application/service/DeliveryServiceImpl.java
  delivery/src/main/java/com/owlexpress/delivery/presentation/DeliveryController.java
Labels: refactor

#317 Refactor(delivery)/refactor delivery usecase
  delivery/src/main/java/com/owlexpress/delivery/application/service/DeliveryUsecase.java
Labels: refactor

#320 [OV-209] refactor(hub): 허브 서비스 service 및 dto 수정 (#319)
  hub/build.gradle
  hub/src/main/java/com/owlexpress/hub/application/HubDistanceService.java
  hub/src/main/java/com/owlexpress/hub/application/HubPathFinder.java
  hub/src/main/java/com/owlexpress/hub/application/HubProductUseCase.java
  hub/src/main/java/com/owlexpress/hub/domain/service/HubProductServiceImpl.java
  hub/src/main/java/com/owlexpress/hub/infrastructure/api/NaverDirectionsClient.java
  hub/src/main/java/com/owlexpress/hub/presentation/dto/request/OrderConfirmRequestDto.java
Labels: refactor

#322 [OV-210] refactor(order): 주문 서비스 feign client 연결 수정 (#321)
  order/src/main/java/com/owlexpress/order/application/dto/request/ConfirmHubStockRequestDto.java
  order/src/main/java/com/owlexpress/order/application/service/OrderServiceImpl.java
  order/src/main/java/com/owlexpress/order/infrastructure/client/HubFeignClient.java
  order/src/main/java/com/owlexpress/order/presentation/dto/request/CreateOrderRequestDto.java
  payment/src/main/java/com/owlexpress/payment/presentation/dto/request/PaymentCreateRequestDto.java
Labels: refactor

#318 [OV-191] refactor(consumer) : 위도 경도 순서 바꿈
  consumer/src/main/java/com/owlexpress/consumer/application/usecase/ConsumerUsecase.java
Labels: refactor

#332 [OV-216] factor(hubIntervalInfo) : 허브이동정보 캐싱 완료
  hub/src/main/java/com/owlexpress/hub/application/HubDistanceService.java
  hub/src/main/java/com/owlexpress/hub/infrastructure/config/RedissonConfig.java
  hub/src/main/java/com/owlexpress/hub/presentation/dto/response/HubIntervalInfoResponse.java
Labels: enhancement

#329 [OV-214] factor(HubDeliveryManager) : 배송담당자 캐싱 적용
  deliveryManager/src/main/java/com/owlexpress/deliverymanager/application/usecase/ConsumerDeliveryManagerUsecase.java
  deliveryManager/src/main/java/com/owlexpress/deliverymanager/application/usecase/HubDeliveryManagerUsecase.java
  deliveryManager/src/main/java/com/owlexpress/deliverymanager/common/exception/ConsumerDeliveryManagerException.java
  deliveryManager/src/main/java/com/owlexpress/deliverymanager/common/exception/ExceptionMessage.java
  deliveryManager/src/main/java/com/owlexpress/deliverymanager/domain/repository/ConsumerDeliveryManagerRepository.java
  deliveryManager/src/main/java/com/owlexpress/deliverymanager/infrastructure/repository/consumer/ConsumerDeliveryManagerJpaRepository.java
  deliveryManager/src/main/java/com/owlexpress/deliverymanager/infrastructure/repository/consumer/ConsumerDeliveryManagerRepositoryImpl.java
  deliveryManager/src/main/java/com/owlexpress/deliverymanager/presentation/controller/ConsumerDeliveryManagerController.java
Labels: enhancement

#333 [OV-215] : refactor(hub) : 재고 감소 기능 분산 락 추가
  hub/src/main/java/com/owlexpress/hub/application/HubProductUseCase.java
  hub/src/main/java/com/owlexpress/hub/common/exception/HubProductException.java
  hub/src/main/java/com/owlexpress/hub/domain/repository/HubProductRepository.java
  hub/src/main/java/com/owlexpress/hub/infrastructure/config/TransactionConfig.java
  hub/src/main/java/com/owlexpress/hub/infrastructure/repository/hubProduct/HubProductRepositoryImpl.java
  hub/src/main/resources/test.js
Labels: enhancement

#335 Refactor(delivery)/cache delivery
  delivery/build.gradle
  delivery/src/main/java/com/owlexpress/delivery/application/dtos/DeliveryCacheDto.java
  delivery/src/main/java/com/owlexpress/delivery/application/service/DeliveryServiceImpl.java
  delivery/src/main/java/com/owlexpress/delivery/domain/entity/Delivery.java
  delivery/src/main/java/com/owlexpress/delivery/domain/entity/DeliveryHistory.java
  delivery/src/main/java/com/owlexpress/delivery/infrastructure/config/FeignOkHttpConfiguration.java
  delivery/src/main/java/com/owlexpress/delivery/infrastructure/config/RedissonConfig.java
  delivery/src/main/java/com/owlexpress/delivery/infrastructure/feignClient/DeliveryManagerClient.java
  docker-compose.yml
Labels: refactor

#336 [OV-217] feat(elk) : ELK 연동
  ai/build.gradle
  ai/src/main/resources/logback.xml
  alarm/build.gradle
  alarm/src/main/java/com/owl_express/alarm/common/aop/AlarmExecutionLoggingAspect.java
  alarm/src/main/resources/logback.xml
  consumer/build.gradle
  consumer/src/main/java/com/owlexpress/consumer/common/aop/ConsumerFindLoggingAspect.java
  consumer/src/main/resources/logback.xml
  delivery/build.gradle
  delivery/src/main/java/com/owlexpress/delivery/common/aop/DeliveryExecutionLoggingAspect.java
  delivery/src/main/resources/logback.xml
  deliveryManager/build.gradle
  deliveryManager/src/main/java/com/owlexpress/deliverymanager/common/aop/DeliveryManagerAssignLoggingAspect.java
  deliveryManager/src/main/java/com/owlexpress/deliverymanager/presentation/controller/ConsumerDeliveryManagerController.java
  deliveryManager/src/main/java/com/owlexpress/deliverymanager/presentation/controller/HubDeliveryManagerController.java
  deliveryManager/src/main/resources/logback.xml
  docker-compose.yml
  hub/build.gradle
  hub/src/main/java/com/owlexpress/hub/common/aop/HubProductOrderLoggingAspect.java
  hub/src/main/java/com/owlexpress/hub/common/aop/HubRouteExecutionLoggingAspect.java
  hub/src/main/resources/logback.xml
  logstash.conf
  order/build.gradle
  order/src/main/java/com/owlexpress/order/common/aop/OrderExecutionLoggingAspect.java
  order/src/main/java/com/owlexpress/order/common/exception/GlobalException.java
  order/src/main/java/com/owlexpress/order/infrastructure/config/RedisConfig.java
  order/src/main/resources/logback.xml
  payment/build.gradle
  payment/src/main/java/com/owlexpress/payment/application/dto/response/RouteResponseDto.java
  payment/src/main/java/com/owlexpress/payment/common/aop/PaymentExecutionLoggingAspect.java
  payment/src/main/resources/logback.xml
  product/build.gradle
  user/src/main/resources/data.sql
Labels: enhancement

#340 Refactor(delivery)/add feign passport
  delivery/src/main/java/com/owlexpress/delivery/application/service/DeliveryServiceImpl.java
  delivery/src/main/java/com/owlexpress/delivery/application/service/DeliveryUsecase.java
  delivery/src/main/java/com/owlexpress/delivery/infrastructure/config/FeignOkHttpConfiguration.java
  delivery/src/main/java/com/owlexpress/delivery/infrastructure/feignClient/DeliveryManagerClient.java
Labels: refactor

#347 Refactor(delivery)/refactor method
  delivery/src/main/java/com/owlexpress/delivery/application/service/DeliveryServiceImpl.java
  hub/src/main/java/com/owlexpress/hub/HubApplication.java
Labels: refactor

#354 [OV-223] chore: 서비스별 DB 분리 및 환경설정 (#353)
  ai/src/main/resources/application.yml
  alarm/src/main/resources/application.yml
  cart/src/main/resources/application.yml
  consumer/src/main/resources/application.yml
  delivery/src/main/resources/application.yml
  deliveryManager/src/main/resources/application.yml
  docker-compose.yml
  hub/src/main/resources/application.yml
  order/src/main/resources/application.yml
  payment/src/main/resources/application.yml
  producer/src/main/resources/application.yml
  product/src/main/resources/application.yml
  user/src/main/resources/application.yml
Labels: chore

#356 Feat(all)/kafka setting
  ai/build.gradle
  ai/src/main/java/com/owl_express/ai/infrastructure/kafka/KafkaConfig.java
  ai/src/main/java/com/owl_express/ai/infrastructure/kafka/KafkaConsumerConfig.java
  ai/src/main/java/com/owl_express/ai/infrastructure/kafka/KafkaProducerConfig.java
  ai/src/main/java/com/owl_express/ai/infrastructure/kafka/KafkaProducerInterceptor.java
  ai/src/main/java/com/owl_express/ai/infrastructure/kafka/KafkaProducerListener.java
  alarm/build.gradle
  alarm/src/main/java/com/owl_express/alarm/infrastructure/kafka/KafkaConfig.java
  alarm/src/main/java/com/owl_express/alarm/infrastructure/kafka/KafkaConsumerConfig.java
  alarm/src/main/java/com/owl_express/alarm/infrastructure/kafka/KafkaProducerConfig.java
  alarm/src/main/java/com/owl_express/alarm/infrastructure/kafka/KafkaProducerInterceptor.java
  alarm/src/main/java/com/owl_express/alarm/infrastructure/kafka/KafkaProducerListener.java
  consumer/build.gradle
  consumer/src/main/java/com/owlexpress/consumer/infrastructure/kafka/KafkaConfig.java
  consumer/src/main/java/com/owlexpress/consumer/infrastructure/kafka/KafkaConsumerConfig.java
  consumer/src/main/java/com/owlexpress/consumer/infrastructure/kafka/KafkaProducerConfig.java
  consumer/src/main/java/com/owlexpress/consumer/infrastructure/kafka/KafkaProducerInterceptor.java
  consumer/src/main/java/com/owlexpress/consumer/infrastructure/kafka/KafkaProducerListener.java
  delivery/build.gradle
  delivery/src/main/java/com/owlexpress/delivery/infrastructure/kafka/KafkaConfig.java
  delivery/src/main/java/com/owlexpress/delivery/infrastructure/kafka/KafkaConsumerConfig.java
  delivery/src/main/java/com/owlexpress/delivery/infrastructure/kafka/KafkaProducerConfig.java
  delivery/src/main/java/com/owlexpress/delivery/infrastructure/kafka/KafkaProducerInterceptor.java
  delivery/src/main/java/com/owlexpress/delivery/infrastructure/kafka/KafkaProducerListener.java
  deliveryManager/build.gradle
  deliveryManager/src/main/java/com/owlexpress/deliverymanager/infrastructure/kafka/KafkaConfig.java
  deliveryManager/src/main/java/com/owlexpress/deliverymanager/infrastructure/kafka/KafkaConsumerConfig.java
  deliveryManager/src/main/java/com/owlexpress/deliverymanager/infrastructure/kafka/KafkaProducerConfig.java
  deliveryManager/src/main/java/com/owlexpress/deliverymanager/infrastructure/kafka/KafkaProducerInterceptor.java
  deliveryManager/src/main/java/com/owlexpress/deliverymanager/infrastructure/kafka/KafkaProducerListener.java
  hub/build.gradle
  hub/src/main/java/com/owlexpress/hub/infrastructure/kafka/KafkaConfig.java
  hub/src/main/java/com/owlexpress/hub/infrastructure/kafka/KafkaConsumerConfig.java
  hub/src/main/java/com/owlexpress/hub/infrastructure/kafka/KafkaProducerConfig.java
  hub/src/main/java/com/owlexpress/hub/infrastructure/kafka/KafkaProducerInterceptor.java
  hub/src/main/java/com/owlexpress/hub/infrastructure/kafka/KafkaProducerListener.java
  order/build.gradle
  order/src/main/java/com/owlexpress/order/infrastructure/kafka/KafkaConfig.java
  order/src/main/java/com/owlexpress/order/infrastructure/kafka/KafkaConsumerConfig.java
  order/src/main/java/com/owlexpress/order/infrastructure/kafka/KafkaProducerConfig.java
  order/src/main/java/com/owlexpress/order/infrastructure/kafka/KafkaProducerInterceptor.java
  order/src/main/java/com/owlexpress/order/infrastructure/kafka/KafkaProducerListener.java
  payment/build.gradle
  payment/src/main/java/com/owlexpress/payment/infrastructure/kafka/KafkaConfig.java
  payment/src/main/java/com/owlexpress/payment/infrastructure/kafka/KafkaConsumerConfig.java
  payment/src/main/java/com/owlexpress/payment/infrastructure/kafka/KafkaProducerConfig.java
  payment/src/main/java/com/owlexpress/payment/infrastructure/kafka/KafkaProducerInterceptor.java
  payment/src/main/java/com/owlexpress/payment/infrastructure/kafka/KafkaProducerListener.java
  product/build.gradle
Labels: enhancement
